<?php

require 'plugins/sfGuardPlugin/lib/model/om/BasesfGuardUserProfile.php';


/**
 * Skeleton subclass for representing a row from the 'sf_guard_user_profile' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * Mon Mar  8 18:11:37 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.sfGuardPlugin.lib.model
 */
class sfGuardUserProfile extends BasesfGuardUserProfile {

} // sfGuardUserProfile
