<?php

/**
 * Base class that represents a row from the 'logicalvolume' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Fri Aug 28 18:22:07 2009
 *
 * @package    lib.model.om
 */
abstract class BaseEtvaLogicalvolume extends BaseObject  implements Persistent {


  const PEER = 'EtvaLogicalvolumePeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        EtvaLogicalvolumePeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the volumegroup_id field.
	 * @var        int
	 */
	protected $volumegroup_id;

	/**
	 * The value for the node_id field.
	 * @var        int
	 */
	protected $node_id;

	/**
	 * The value for the lv field.
	 * @var        string
	 */
	protected $lv;

	/**
	 * The value for the lvdevice field.
	 * @var        string
	 */
	protected $lvdevice;

	/**
	 * The value for the size field.
	 * @var        string
	 */
	protected $size;

	/**
	 * The value for the freesize field.
	 * @var        string
	 */
	protected $freesize;

	/**
	 * The value for the storage_type field.
	 * @var        string
	 */
	protected $storage_type;

	/**
	 * The value for the writeable field.
	 * @var        int
	 */
	protected $writeable;

	/**
	 * The value for the in_use field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $in_use;

	/**
	 * The value for the target field.
	 * @var        string
	 */
	protected $target;

	/**
	 * @var        EtvaVolumegroup
	 */
	protected $aEtvaVolumegroup;

	/**
	 * @var        EtvaNode
	 */
	protected $aEtvaNode;

	/**
	 * @var        array EtvaServer[] Collection to store aggregation of EtvaServer objects.
	 */
	protected $collEtvaServers;

	/**
	 * @var        Criteria The criteria used to select the current contents of collEtvaServers.
	 */
	private $lastEtvaServerCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseEtvaLogicalvolume object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->in_use = 0;
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [volumegroup_id] column value.
	 * 
	 * @return     int
	 */
	public function getVolumegroupId()
	{
		return $this->volumegroup_id;
	}

	/**
	 * Get the [node_id] column value.
	 * 
	 * @return     int
	 */
	public function getNodeId()
	{
		return $this->node_id;
	}

	/**
	 * Get the [lv] column value.
	 * 
	 * @return     string
	 */
	public function getLv()
	{
		return $this->lv;
	}

	/**
	 * Get the [lvdevice] column value.
	 * 
	 * @return     string
	 */
	public function getLvdevice()
	{
		return $this->lvdevice;
	}

	/**
	 * Get the [size] column value.
	 * 
	 * @return     string
	 */
	public function getSize()
	{
		return $this->size;
	}

	/**
	 * Get the [freesize] column value.
	 * 
	 * @return     string
	 */
	public function getFreesize()
	{
		return $this->freesize;
	}

	/**
	 * Get the [storage_type] column value.
	 * 
	 * @return     string
	 */
	public function getStorageType()
	{
		return $this->storage_type;
	}

	/**
	 * Get the [writeable] column value.
	 * 
	 * @return     int
	 */
	public function getWriteable()
	{
		return $this->writeable;
	}

	/**
	 * Get the [in_use] column value.
	 * 
	 * @return     int
	 */
	public function getInUse()
	{
		return $this->in_use;
	}

	/**
	 * Get the [target] column value.
	 * 
	 * @return     string
	 */
	public function getTarget()
	{
		return $this->target;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     EtvaLogicalvolume The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = EtvaLogicalvolumePeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [volumegroup_id] column.
	 * 
	 * @param      int $v new value
	 * @return     EtvaLogicalvolume The current object (for fluent API support)
	 */
	public function setVolumegroupId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->volumegroup_id !== $v) {
			$this->volumegroup_id = $v;
			$this->modifiedColumns[] = EtvaLogicalvolumePeer::VOLUMEGROUP_ID;
		}

		if ($this->aEtvaVolumegroup !== null && $this->aEtvaVolumegroup->getId() !== $v) {
			$this->aEtvaVolumegroup = null;
		}

		return $this;
	} // setVolumegroupId()

	/**
	 * Set the value of [node_id] column.
	 * 
	 * @param      int $v new value
	 * @return     EtvaLogicalvolume The current object (for fluent API support)
	 */
	public function setNodeId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->node_id !== $v) {
			$this->node_id = $v;
			$this->modifiedColumns[] = EtvaLogicalvolumePeer::NODE_ID;
		}

		if ($this->aEtvaNode !== null && $this->aEtvaNode->getId() !== $v) {
			$this->aEtvaNode = null;
		}

		return $this;
	} // setNodeId()

	/**
	 * Set the value of [lv] column.
	 * 
	 * @param      string $v new value
	 * @return     EtvaLogicalvolume The current object (for fluent API support)
	 */
	public function setLv($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->lv !== $v) {
			$this->lv = $v;
			$this->modifiedColumns[] = EtvaLogicalvolumePeer::LV;
		}

		return $this;
	} // setLv()

	/**
	 * Set the value of [lvdevice] column.
	 * 
	 * @param      string $v new value
	 * @return     EtvaLogicalvolume The current object (for fluent API support)
	 */
	public function setLvdevice($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->lvdevice !== $v) {
			$this->lvdevice = $v;
			$this->modifiedColumns[] = EtvaLogicalvolumePeer::LVDEVICE;
		}

		return $this;
	} // setLvdevice()

	/**
	 * Set the value of [size] column.
	 * 
	 * @param      string $v new value
	 * @return     EtvaLogicalvolume The current object (for fluent API support)
	 */
	public function setSize($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->size !== $v) {
			$this->size = $v;
			$this->modifiedColumns[] = EtvaLogicalvolumePeer::SIZE;
		}

		return $this;
	} // setSize()

	/**
	 * Set the value of [freesize] column.
	 * 
	 * @param      string $v new value
	 * @return     EtvaLogicalvolume The current object (for fluent API support)
	 */
	public function setFreesize($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->freesize !== $v) {
			$this->freesize = $v;
			$this->modifiedColumns[] = EtvaLogicalvolumePeer::FREESIZE;
		}

		return $this;
	} // setFreesize()

	/**
	 * Set the value of [storage_type] column.
	 * 
	 * @param      string $v new value
	 * @return     EtvaLogicalvolume The current object (for fluent API support)
	 */
	public function setStorageType($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->storage_type !== $v) {
			$this->storage_type = $v;
			$this->modifiedColumns[] = EtvaLogicalvolumePeer::STORAGE_TYPE;
		}

		return $this;
	} // setStorageType()

	/**
	 * Set the value of [writeable] column.
	 * 
	 * @param      int $v new value
	 * @return     EtvaLogicalvolume The current object (for fluent API support)
	 */
	public function setWriteable($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->writeable !== $v) {
			$this->writeable = $v;
			$this->modifiedColumns[] = EtvaLogicalvolumePeer::WRITEABLE;
		}

		return $this;
	} // setWriteable()

	/**
	 * Set the value of [in_use] column.
	 * 
	 * @param      int $v new value
	 * @return     EtvaLogicalvolume The current object (for fluent API support)
	 */
	public function setInUse($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->in_use !== $v || $v === 0) {
			$this->in_use = $v;
			$this->modifiedColumns[] = EtvaLogicalvolumePeer::IN_USE;
		}

		return $this;
	} // setInUse()

	/**
	 * Set the value of [target] column.
	 * 
	 * @param      string $v new value
	 * @return     EtvaLogicalvolume The current object (for fluent API support)
	 */
	public function setTarget($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->target !== $v) {
			$this->target = $v;
			$this->modifiedColumns[] = EtvaLogicalvolumePeer::TARGET;
		}

		return $this;
	} // setTarget()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array(EtvaLogicalvolumePeer::IN_USE))) {
				return false;
			}

			if ($this->in_use !== 0) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->volumegroup_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->node_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->lv = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->lvdevice = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->size = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->freesize = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->storage_type = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->writeable = ($row[$startcol + 8] !== null) ? (int) $row[$startcol + 8] : null;
			$this->in_use = ($row[$startcol + 9] !== null) ? (int) $row[$startcol + 9] : null;
			$this->target = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 11; // 11 = EtvaLogicalvolumePeer::NUM_COLUMNS - EtvaLogicalvolumePeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating EtvaLogicalvolume object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aEtvaVolumegroup !== null && $this->volumegroup_id !== $this->aEtvaVolumegroup->getId()) {
			$this->aEtvaVolumegroup = null;
		}
		if ($this->aEtvaNode !== null && $this->node_id !== $this->aEtvaNode->getId()) {
			$this->aEtvaNode = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(EtvaLogicalvolumePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = EtvaLogicalvolumePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aEtvaVolumegroup = null;
			$this->aEtvaNode = null;
			$this->collEtvaServers = null;
			$this->lastEtvaServerCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseEtvaLogicalvolume:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(EtvaLogicalvolumePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			EtvaLogicalvolumePeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseEtvaLogicalvolume:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseEtvaLogicalvolume:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(EtvaLogicalvolumePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseEtvaLogicalvolume:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			EtvaLogicalvolumePeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aEtvaVolumegroup !== null) {
				if ($this->aEtvaVolumegroup->isModified() || $this->aEtvaVolumegroup->isNew()) {
					$affectedRows += $this->aEtvaVolumegroup->save($con);
				}
				$this->setEtvaVolumegroup($this->aEtvaVolumegroup);
			}

			if ($this->aEtvaNode !== null) {
				if ($this->aEtvaNode->isModified() || $this->aEtvaNode->isNew()) {
					$affectedRows += $this->aEtvaNode->save($con);
				}
				$this->setEtvaNode($this->aEtvaNode);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = EtvaLogicalvolumePeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = EtvaLogicalvolumePeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += EtvaLogicalvolumePeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collEtvaServers !== null) {
				foreach ($this->collEtvaServers as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aEtvaVolumegroup !== null) {
				if (!$this->aEtvaVolumegroup->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aEtvaVolumegroup->getValidationFailures());
				}
			}

			if ($this->aEtvaNode !== null) {
				if (!$this->aEtvaNode->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aEtvaNode->getValidationFailures());
				}
			}


			if (($retval = EtvaLogicalvolumePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collEtvaServers !== null) {
					foreach ($this->collEtvaServers as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = EtvaLogicalvolumePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getVolumegroupId();
				break;
			case 2:
				return $this->getNodeId();
				break;
			case 3:
				return $this->getLv();
				break;
			case 4:
				return $this->getLvdevice();
				break;
			case 5:
				return $this->getSize();
				break;
			case 6:
				return $this->getFreesize();
				break;
			case 7:
				return $this->getStorageType();
				break;
			case 8:
				return $this->getWriteable();
				break;
			case 9:
				return $this->getInUse();
				break;
			case 10:
				return $this->getTarget();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = EtvaLogicalvolumePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getVolumegroupId(),
			$keys[2] => $this->getNodeId(),
			$keys[3] => $this->getLv(),
			$keys[4] => $this->getLvdevice(),
			$keys[5] => $this->getSize(),
			$keys[6] => $this->getFreesize(),
			$keys[7] => $this->getStorageType(),
			$keys[8] => $this->getWriteable(),
			$keys[9] => $this->getInUse(),
			$keys[10] => $this->getTarget(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = EtvaLogicalvolumePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setVolumegroupId($value);
				break;
			case 2:
				$this->setNodeId($value);
				break;
			case 3:
				$this->setLv($value);
				break;
			case 4:
				$this->setLvdevice($value);
				break;
			case 5:
				$this->setSize($value);
				break;
			case 6:
				$this->setFreesize($value);
				break;
			case 7:
				$this->setStorageType($value);
				break;
			case 8:
				$this->setWriteable($value);
				break;
			case 9:
				$this->setInUse($value);
				break;
			case 10:
				$this->setTarget($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = EtvaLogicalvolumePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setVolumegroupId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setNodeId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setLv($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setLvdevice($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setSize($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setFreesize($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setStorageType($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setWriteable($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setInUse($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setTarget($arr[$keys[10]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(EtvaLogicalvolumePeer::DATABASE_NAME);

		if ($this->isColumnModified(EtvaLogicalvolumePeer::ID)) $criteria->add(EtvaLogicalvolumePeer::ID, $this->id);
		if ($this->isColumnModified(EtvaLogicalvolumePeer::VOLUMEGROUP_ID)) $criteria->add(EtvaLogicalvolumePeer::VOLUMEGROUP_ID, $this->volumegroup_id);
		if ($this->isColumnModified(EtvaLogicalvolumePeer::NODE_ID)) $criteria->add(EtvaLogicalvolumePeer::NODE_ID, $this->node_id);
		if ($this->isColumnModified(EtvaLogicalvolumePeer::LV)) $criteria->add(EtvaLogicalvolumePeer::LV, $this->lv);
		if ($this->isColumnModified(EtvaLogicalvolumePeer::LVDEVICE)) $criteria->add(EtvaLogicalvolumePeer::LVDEVICE, $this->lvdevice);
		if ($this->isColumnModified(EtvaLogicalvolumePeer::SIZE)) $criteria->add(EtvaLogicalvolumePeer::SIZE, $this->size);
		if ($this->isColumnModified(EtvaLogicalvolumePeer::FREESIZE)) $criteria->add(EtvaLogicalvolumePeer::FREESIZE, $this->freesize);
		if ($this->isColumnModified(EtvaLogicalvolumePeer::STORAGE_TYPE)) $criteria->add(EtvaLogicalvolumePeer::STORAGE_TYPE, $this->storage_type);
		if ($this->isColumnModified(EtvaLogicalvolumePeer::WRITEABLE)) $criteria->add(EtvaLogicalvolumePeer::WRITEABLE, $this->writeable);
		if ($this->isColumnModified(EtvaLogicalvolumePeer::IN_USE)) $criteria->add(EtvaLogicalvolumePeer::IN_USE, $this->in_use);
		if ($this->isColumnModified(EtvaLogicalvolumePeer::TARGET)) $criteria->add(EtvaLogicalvolumePeer::TARGET, $this->target);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(EtvaLogicalvolumePeer::DATABASE_NAME);

		$criteria->add(EtvaLogicalvolumePeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of EtvaLogicalvolume (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setVolumegroupId($this->volumegroup_id);

		$copyObj->setNodeId($this->node_id);

		$copyObj->setLv($this->lv);

		$copyObj->setLvdevice($this->lvdevice);

		$copyObj->setSize($this->size);

		$copyObj->setFreesize($this->freesize);

		$copyObj->setStorageType($this->storage_type);

		$copyObj->setWriteable($this->writeable);

		$copyObj->setInUse($this->in_use);

		$copyObj->setTarget($this->target);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getEtvaServers() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addEtvaServer($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     EtvaLogicalvolume Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     EtvaLogicalvolumePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new EtvaLogicalvolumePeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a EtvaVolumegroup object.
	 *
	 * @param      EtvaVolumegroup $v
	 * @return     EtvaLogicalvolume The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setEtvaVolumegroup(EtvaVolumegroup $v = null)
	{
		if ($v === null) {
			$this->setVolumegroupId(NULL);
		} else {
			$this->setVolumegroupId($v->getId());
		}

		$this->aEtvaVolumegroup = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the EtvaVolumegroup object, it will not be re-added.
		if ($v !== null) {
			$v->addEtvaLogicalvolume($this);
		}

		return $this;
	}


	/**
	 * Get the associated EtvaVolumegroup object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     EtvaVolumegroup The associated EtvaVolumegroup object.
	 * @throws     PropelException
	 */
	public function getEtvaVolumegroup(PropelPDO $con = null)
	{
		if ($this->aEtvaVolumegroup === null && ($this->volumegroup_id !== null)) {
			$c = new Criteria(EtvaVolumegroupPeer::DATABASE_NAME);
			$c->add(EtvaVolumegroupPeer::ID, $this->volumegroup_id);
			$this->aEtvaVolumegroup = EtvaVolumegroupPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aEtvaVolumegroup->addEtvaLogicalvolumes($this);
			 */
		}
		return $this->aEtvaVolumegroup;
	}

	/**
	 * Declares an association between this object and a EtvaNode object.
	 *
	 * @param      EtvaNode $v
	 * @return     EtvaLogicalvolume The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setEtvaNode(EtvaNode $v = null)
	{
		if ($v === null) {
			$this->setNodeId(NULL);
		} else {
			$this->setNodeId($v->getId());
		}

		$this->aEtvaNode = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the EtvaNode object, it will not be re-added.
		if ($v !== null) {
			$v->addEtvaLogicalvolume($this);
		}

		return $this;
	}


	/**
	 * Get the associated EtvaNode object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     EtvaNode The associated EtvaNode object.
	 * @throws     PropelException
	 */
	public function getEtvaNode(PropelPDO $con = null)
	{
		if ($this->aEtvaNode === null && ($this->node_id !== null)) {
			$c = new Criteria(EtvaNodePeer::DATABASE_NAME);
			$c->add(EtvaNodePeer::ID, $this->node_id);
			$this->aEtvaNode = EtvaNodePeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aEtvaNode->addEtvaLogicalvolumes($this);
			 */
		}
		return $this->aEtvaNode;
	}

	/**
	 * Clears out the collEtvaServers collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addEtvaServers()
	 */
	public function clearEtvaServers()
	{
		$this->collEtvaServers = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collEtvaServers collection (array).
	 *
	 * By default this just sets the collEtvaServers collection to an empty array (like clearcollEtvaServers());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initEtvaServers()
	{
		$this->collEtvaServers = array();
	}

	/**
	 * Gets an array of EtvaServer objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this EtvaLogicalvolume has previously been saved, it will retrieve
	 * related EtvaServers from storage. If this EtvaLogicalvolume is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array EtvaServer[]
	 * @throws     PropelException
	 */
	public function getEtvaServers($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EtvaLogicalvolumePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collEtvaServers === null) {
			if ($this->isNew()) {
			   $this->collEtvaServers = array();
			} else {

				$criteria->add(EtvaServerPeer::LOGICALVOLUME_ID, $this->id);

				EtvaServerPeer::addSelectColumns($criteria);
				$this->collEtvaServers = EtvaServerPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(EtvaServerPeer::LOGICALVOLUME_ID, $this->id);

				EtvaServerPeer::addSelectColumns($criteria);
				if (!isset($this->lastEtvaServerCriteria) || !$this->lastEtvaServerCriteria->equals($criteria)) {
					$this->collEtvaServers = EtvaServerPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastEtvaServerCriteria = $criteria;
		return $this->collEtvaServers;
	}

	/**
	 * Returns the number of related EtvaServer objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related EtvaServer objects.
	 * @throws     PropelException
	 */
	public function countEtvaServers(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EtvaLogicalvolumePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collEtvaServers === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(EtvaServerPeer::LOGICALVOLUME_ID, $this->id);

				$count = EtvaServerPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(EtvaServerPeer::LOGICALVOLUME_ID, $this->id);

				if (!isset($this->lastEtvaServerCriteria) || !$this->lastEtvaServerCriteria->equals($criteria)) {
					$count = EtvaServerPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collEtvaServers);
				}
			} else {
				$count = count($this->collEtvaServers);
			}
		}
		$this->lastEtvaServerCriteria = $criteria;
		return $count;
	}

	/**
	 * Method called to associate a EtvaServer object to this object
	 * through the EtvaServer foreign key attribute.
	 *
	 * @param      EtvaServer $l EtvaServer
	 * @return     void
	 * @throws     PropelException
	 */
	public function addEtvaServer(EtvaServer $l)
	{
		if ($this->collEtvaServers === null) {
			$this->initEtvaServers();
		}
		if (!in_array($l, $this->collEtvaServers, true)) { // only add it if the **same** object is not already associated
			array_push($this->collEtvaServers, $l);
			$l->setEtvaLogicalvolume($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this EtvaLogicalvolume is new, it will return
	 * an empty collection; or if this EtvaLogicalvolume has previously
	 * been saved, it will retrieve related EtvaServers from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in EtvaLogicalvolume.
	 */
	public function getEtvaServersJoinEtvaNode($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EtvaLogicalvolumePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collEtvaServers === null) {
			if ($this->isNew()) {
				$this->collEtvaServers = array();
			} else {

				$criteria->add(EtvaServerPeer::LOGICALVOLUME_ID, $this->id);

				$this->collEtvaServers = EtvaServerPeer::doSelectJoinEtvaNode($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(EtvaServerPeer::LOGICALVOLUME_ID, $this->id);

			if (!isset($this->lastEtvaServerCriteria) || !$this->lastEtvaServerCriteria->equals($criteria)) {
				$this->collEtvaServers = EtvaServerPeer::doSelectJoinEtvaNode($criteria, $con, $join_behavior);
			}
		}
		$this->lastEtvaServerCriteria = $criteria;

		return $this->collEtvaServers;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this EtvaLogicalvolume is new, it will return
	 * an empty collection; or if this EtvaLogicalvolume has previously
	 * been saved, it will retrieve related EtvaServers from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in EtvaLogicalvolume.
	 */
	public function getEtvaServersJoinsfGuardGroup($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EtvaLogicalvolumePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collEtvaServers === null) {
			if ($this->isNew()) {
				$this->collEtvaServers = array();
			} else {

				$criteria->add(EtvaServerPeer::LOGICALVOLUME_ID, $this->id);

				$this->collEtvaServers = EtvaServerPeer::doSelectJoinsfGuardGroup($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(EtvaServerPeer::LOGICALVOLUME_ID, $this->id);

			if (!isset($this->lastEtvaServerCriteria) || !$this->lastEtvaServerCriteria->equals($criteria)) {
				$this->collEtvaServers = EtvaServerPeer::doSelectJoinsfGuardGroup($criteria, $con, $join_behavior);
			}
		}
		$this->lastEtvaServerCriteria = $criteria;

		return $this->collEtvaServers;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collEtvaServers) {
				foreach ((array) $this->collEtvaServers as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collEtvaServers = null;
			$this->aEtvaVolumegroup = null;
			$this->aEtvaNode = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseEtvaLogicalvolume:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseEtvaLogicalvolume::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseEtvaLogicalvolume
