<?php

/**
 * Base static class for performing query and update operations on the 'logicalvolume' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Fri Aug 28 18:22:07 2009
 *
 * @package    lib.model.om
 */
abstract class BaseEtvaLogicalvolumePeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'logicalvolume';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.EtvaLogicalvolume';

	/** The total number of columns. */
	const NUM_COLUMNS = 11;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the ID field */
	const ID = 'logicalvolume.ID';

	/** the column name for the VOLUMEGROUP_ID field */
	const VOLUMEGROUP_ID = 'logicalvolume.VOLUMEGROUP_ID';

	/** the column name for the NODE_ID field */
	const NODE_ID = 'logicalvolume.NODE_ID';

	/** the column name for the LV field */
	const LV = 'logicalvolume.LV';

	/** the column name for the LVDEVICE field */
	const LVDEVICE = 'logicalvolume.LVDEVICE';

	/** the column name for the SIZE field */
	const SIZE = 'logicalvolume.SIZE';

	/** the column name for the FREESIZE field */
	const FREESIZE = 'logicalvolume.FREESIZE';

	/** the column name for the STORAGE_TYPE field */
	const STORAGE_TYPE = 'logicalvolume.STORAGE_TYPE';

	/** the column name for the WRITEABLE field */
	const WRITEABLE = 'logicalvolume.WRITEABLE';

	/** the column name for the IN_USE field */
	const IN_USE = 'logicalvolume.IN_USE';

	/** the column name for the TARGET field */
	const TARGET = 'logicalvolume.TARGET';

	/**
	 * An identiy map to hold any loaded instances of EtvaLogicalvolume objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array EtvaLogicalvolume[]
	 */
	public static $instances = array();

	/**
	 * The MapBuilder instance for this peer.
	 * @var        MapBuilder
	 */
	private static $mapBuilder = null;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('Id', 'VolumegroupId', 'NodeId', 'Lv', 'Lvdevice', 'Size', 'Freesize', 'StorageType', 'Writeable', 'InUse', 'Target', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id', 'volumegroupId', 'nodeId', 'lv', 'lvdevice', 'size', 'freesize', 'storageType', 'writeable', 'inUse', 'target', ),
		BasePeer::TYPE_COLNAME => array (self::ID, self::VOLUMEGROUP_ID, self::NODE_ID, self::LV, self::LVDEVICE, self::SIZE, self::FREESIZE, self::STORAGE_TYPE, self::WRITEABLE, self::IN_USE, self::TARGET, ),
		BasePeer::TYPE_FIELDNAME => array ('id', 'volumegroup_id', 'node_id', 'lv', 'lvdevice', 'size', 'freesize', 'storage_type', 'writeable', 'in_use', 'target', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('Id' => 0, 'VolumegroupId' => 1, 'NodeId' => 2, 'Lv' => 3, 'Lvdevice' => 4, 'Size' => 5, 'Freesize' => 6, 'StorageType' => 7, 'Writeable' => 8, 'InUse' => 9, 'Target' => 10, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id' => 0, 'volumegroupId' => 1, 'nodeId' => 2, 'lv' => 3, 'lvdevice' => 4, 'size' => 5, 'freesize' => 6, 'storageType' => 7, 'writeable' => 8, 'inUse' => 9, 'target' => 10, ),
		BasePeer::TYPE_COLNAME => array (self::ID => 0, self::VOLUMEGROUP_ID => 1, self::NODE_ID => 2, self::LV => 3, self::LVDEVICE => 4, self::SIZE => 5, self::FREESIZE => 6, self::STORAGE_TYPE => 7, self::WRITEABLE => 8, self::IN_USE => 9, self::TARGET => 10, ),
		BasePeer::TYPE_FIELDNAME => array ('id' => 0, 'volumegroup_id' => 1, 'node_id' => 2, 'lv' => 3, 'lvdevice' => 4, 'size' => 5, 'freesize' => 6, 'storage_type' => 7, 'writeable' => 8, 'in_use' => 9, 'target' => 10, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, )
	);

	/**
	 * Get a (singleton) instance of the MapBuilder for this peer class.
	 * @return     MapBuilder The map builder for this peer
	 */
	public static function getMapBuilder()
	{
		if (self::$mapBuilder === null) {
			self::$mapBuilder = new EtvaLogicalvolumeMapBuilder();
		}
		return self::$mapBuilder;
	}
	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. EtvaLogicalvolumePeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(EtvaLogicalvolumePeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{

		$criteria->addSelectColumn(EtvaLogicalvolumePeer::ID);

		$criteria->addSelectColumn(EtvaLogicalvolumePeer::VOLUMEGROUP_ID);

		$criteria->addSelectColumn(EtvaLogicalvolumePeer::NODE_ID);

		$criteria->addSelectColumn(EtvaLogicalvolumePeer::LV);

		$criteria->addSelectColumn(EtvaLogicalvolumePeer::LVDEVICE);

		$criteria->addSelectColumn(EtvaLogicalvolumePeer::SIZE);

		$criteria->addSelectColumn(EtvaLogicalvolumePeer::FREESIZE);

		$criteria->addSelectColumn(EtvaLogicalvolumePeer::STORAGE_TYPE);

		$criteria->addSelectColumn(EtvaLogicalvolumePeer::WRITEABLE);

		$criteria->addSelectColumn(EtvaLogicalvolumePeer::IN_USE);

		$criteria->addSelectColumn(EtvaLogicalvolumePeer::TARGET);

	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(EtvaLogicalvolumePeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			EtvaLogicalvolumePeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(EtvaLogicalvolumePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}


    foreach (sfMixer::getCallables('BaseEtvaLogicalvolumePeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseEtvaLogicalvolumePeer', $criteria, $con);
    }


		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     EtvaLogicalvolume
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = EtvaLogicalvolumePeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return EtvaLogicalvolumePeer::populateObjects(EtvaLogicalvolumePeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseEtvaLogicalvolumePeer:doSelectStmt:doSelectStmt') as $callable)
    {
      call_user_func($callable, 'BaseEtvaLogicalvolumePeer', $criteria, $con);
    }


		if ($con === null) {
			$con = Propel::getConnection(EtvaLogicalvolumePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			EtvaLogicalvolumePeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      EtvaLogicalvolume $value A EtvaLogicalvolume object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(EtvaLogicalvolume $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getId();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A EtvaLogicalvolume object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof EtvaLogicalvolume) {
				$key = (string) $value->getId();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or EtvaLogicalvolume object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     EtvaLogicalvolume Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol + 0] === null) {
			return null;
		}
		return (string) $row[$startcol + 0];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = EtvaLogicalvolumePeer::getOMClass();
		$cls = substr('.'.$cls, strrpos('.'.$cls, '.') + 1);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = EtvaLogicalvolumePeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = EtvaLogicalvolumePeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
		
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				EtvaLogicalvolumePeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}

	/**
	 * Returns the number of rows matching criteria, joining the related EtvaVolumegroup table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinEtvaVolumegroup(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(EtvaLogicalvolumePeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			EtvaLogicalvolumePeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(EtvaLogicalvolumePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(EtvaLogicalvolumePeer::VOLUMEGROUP_ID,), array(EtvaVolumegroupPeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseEtvaLogicalvolumePeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseEtvaLogicalvolumePeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related EtvaNode table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinEtvaNode(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(EtvaLogicalvolumePeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			EtvaLogicalvolumePeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(EtvaLogicalvolumePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(EtvaLogicalvolumePeer::NODE_ID,), array(EtvaNodePeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseEtvaLogicalvolumePeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseEtvaLogicalvolumePeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of EtvaLogicalvolume objects pre-filled with their EtvaVolumegroup objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of EtvaLogicalvolume objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinEtvaVolumegroup(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseEtvaLogicalvolumePeer:doSelectJoin:doSelectJoin') as $callable)
    {
      call_user_func($callable, 'BaseEtvaLogicalvolumePeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		EtvaLogicalvolumePeer::addSelectColumns($c);
		$startcol = (EtvaLogicalvolumePeer::NUM_COLUMNS - EtvaLogicalvolumePeer::NUM_LAZY_LOAD_COLUMNS);
		EtvaVolumegroupPeer::addSelectColumns($c);

		$c->addJoin(array(EtvaLogicalvolumePeer::VOLUMEGROUP_ID,), array(EtvaVolumegroupPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = EtvaLogicalvolumePeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = EtvaLogicalvolumePeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = EtvaLogicalvolumePeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				EtvaLogicalvolumePeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = EtvaVolumegroupPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = EtvaVolumegroupPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = EtvaVolumegroupPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					EtvaVolumegroupPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (EtvaLogicalvolume) to $obj2 (EtvaVolumegroup)
				$obj2->addEtvaLogicalvolume($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of EtvaLogicalvolume objects pre-filled with their EtvaNode objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of EtvaLogicalvolume objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinEtvaNode(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		EtvaLogicalvolumePeer::addSelectColumns($c);
		$startcol = (EtvaLogicalvolumePeer::NUM_COLUMNS - EtvaLogicalvolumePeer::NUM_LAZY_LOAD_COLUMNS);
		EtvaNodePeer::addSelectColumns($c);

		$c->addJoin(array(EtvaLogicalvolumePeer::NODE_ID,), array(EtvaNodePeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = EtvaLogicalvolumePeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = EtvaLogicalvolumePeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = EtvaLogicalvolumePeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				EtvaLogicalvolumePeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = EtvaNodePeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = EtvaNodePeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = EtvaNodePeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					EtvaNodePeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (EtvaLogicalvolume) to $obj2 (EtvaNode)
				$obj2->addEtvaLogicalvolume($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining all related tables
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAll(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(EtvaLogicalvolumePeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			EtvaLogicalvolumePeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(EtvaLogicalvolumePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(EtvaLogicalvolumePeer::VOLUMEGROUP_ID,), array(EtvaVolumegroupPeer::ID,), $join_behavior);
		$criteria->addJoin(array(EtvaLogicalvolumePeer::NODE_ID,), array(EtvaNodePeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseEtvaLogicalvolumePeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseEtvaLogicalvolumePeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}

	/**
	 * Selects a collection of EtvaLogicalvolume objects pre-filled with all related objects.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of EtvaLogicalvolume objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAll(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseEtvaLogicalvolumePeer:doSelectJoinAll:doSelectJoinAll') as $callable)
    {
      call_user_func($callable, 'BaseEtvaLogicalvolumePeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		EtvaLogicalvolumePeer::addSelectColumns($c);
		$startcol2 = (EtvaLogicalvolumePeer::NUM_COLUMNS - EtvaLogicalvolumePeer::NUM_LAZY_LOAD_COLUMNS);

		EtvaVolumegroupPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (EtvaVolumegroupPeer::NUM_COLUMNS - EtvaVolumegroupPeer::NUM_LAZY_LOAD_COLUMNS);

		EtvaNodePeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (EtvaNodePeer::NUM_COLUMNS - EtvaNodePeer::NUM_LAZY_LOAD_COLUMNS);

		$c->addJoin(array(EtvaLogicalvolumePeer::VOLUMEGROUP_ID,), array(EtvaVolumegroupPeer::ID,), $join_behavior);
		$c->addJoin(array(EtvaLogicalvolumePeer::NODE_ID,), array(EtvaNodePeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = EtvaLogicalvolumePeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = EtvaLogicalvolumePeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = EtvaLogicalvolumePeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				EtvaLogicalvolumePeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

			// Add objects for joined EtvaVolumegroup rows

			$key2 = EtvaVolumegroupPeer::getPrimaryKeyHashFromRow($row, $startcol2);
			if ($key2 !== null) {
				$obj2 = EtvaVolumegroupPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = EtvaVolumegroupPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					EtvaVolumegroupPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 loaded

				// Add the $obj1 (EtvaLogicalvolume) to the collection in $obj2 (EtvaVolumegroup)
				$obj2->addEtvaLogicalvolume($obj1);
			} // if joined row not null

			// Add objects for joined EtvaNode rows

			$key3 = EtvaNodePeer::getPrimaryKeyHashFromRow($row, $startcol3);
			if ($key3 !== null) {
				$obj3 = EtvaNodePeer::getInstanceFromPool($key3);
				if (!$obj3) {

					$omClass = EtvaNodePeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					EtvaNodePeer::addInstanceToPool($obj3, $key3);
				} // if obj3 loaded

				// Add the $obj1 (EtvaLogicalvolume) to the collection in $obj3 (EtvaNode)
				$obj3->addEtvaLogicalvolume($obj1);
			} // if joined row not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related EtvaVolumegroup table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptEtvaVolumegroup(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			EtvaLogicalvolumePeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(EtvaLogicalvolumePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(EtvaLogicalvolumePeer::NODE_ID,), array(EtvaNodePeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseEtvaLogicalvolumePeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseEtvaLogicalvolumePeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related EtvaNode table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptEtvaNode(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			EtvaLogicalvolumePeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(EtvaLogicalvolumePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(EtvaLogicalvolumePeer::VOLUMEGROUP_ID,), array(EtvaVolumegroupPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseEtvaLogicalvolumePeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseEtvaLogicalvolumePeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of EtvaLogicalvolume objects pre-filled with all related objects except EtvaVolumegroup.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of EtvaLogicalvolume objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptEtvaVolumegroup(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseEtvaLogicalvolumePeer:doSelectJoinAllExcept:doSelectJoinAllExcept') as $callable)
    {
      call_user_func($callable, 'BaseEtvaLogicalvolumePeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		EtvaLogicalvolumePeer::addSelectColumns($c);
		$startcol2 = (EtvaLogicalvolumePeer::NUM_COLUMNS - EtvaLogicalvolumePeer::NUM_LAZY_LOAD_COLUMNS);

		EtvaNodePeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (EtvaNodePeer::NUM_COLUMNS - EtvaNodePeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(EtvaLogicalvolumePeer::NODE_ID,), array(EtvaNodePeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = EtvaLogicalvolumePeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = EtvaLogicalvolumePeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = EtvaLogicalvolumePeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				EtvaLogicalvolumePeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined EtvaNode rows

				$key2 = EtvaNodePeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = EtvaNodePeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = EtvaNodePeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					EtvaNodePeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (EtvaLogicalvolume) to the collection in $obj2 (EtvaNode)
				$obj2->addEtvaLogicalvolume($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of EtvaLogicalvolume objects pre-filled with all related objects except EtvaNode.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of EtvaLogicalvolume objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptEtvaNode(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		EtvaLogicalvolumePeer::addSelectColumns($c);
		$startcol2 = (EtvaLogicalvolumePeer::NUM_COLUMNS - EtvaLogicalvolumePeer::NUM_LAZY_LOAD_COLUMNS);

		EtvaVolumegroupPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (EtvaVolumegroupPeer::NUM_COLUMNS - EtvaVolumegroupPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(EtvaLogicalvolumePeer::VOLUMEGROUP_ID,), array(EtvaVolumegroupPeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = EtvaLogicalvolumePeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = EtvaLogicalvolumePeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = EtvaLogicalvolumePeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				EtvaLogicalvolumePeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined EtvaVolumegroup rows

				$key2 = EtvaVolumegroupPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = EtvaVolumegroupPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = EtvaVolumegroupPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					EtvaVolumegroupPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (EtvaLogicalvolume) to the collection in $obj2 (EtvaVolumegroup)
				$obj2->addEtvaLogicalvolume($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


  static public function getUniqueColumnNames()
  {
    return array();
  }
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * This uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass()
	{
		return EtvaLogicalvolumePeer::CLASS_DEFAULT;
	}

	/**
	 * Method perform an INSERT on the database, given a EtvaLogicalvolume or Criteria object.
	 *
	 * @param      mixed $values Criteria or EtvaLogicalvolume object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseEtvaLogicalvolumePeer:doInsert:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseEtvaLogicalvolumePeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(EtvaLogicalvolumePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from EtvaLogicalvolume object
		}

		if ($criteria->containsKey(EtvaLogicalvolumePeer::ID) && $criteria->keyContainsValue(EtvaLogicalvolumePeer::ID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.EtvaLogicalvolumePeer::ID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

		
    foreach (sfMixer::getCallables('BaseEtvaLogicalvolumePeer:doInsert:post') as $callable)
    {
      call_user_func($callable, 'BaseEtvaLogicalvolumePeer', $values, $con, $pk);
    }

    return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a EtvaLogicalvolume or Criteria object.
	 *
	 * @param      mixed $values Criteria or EtvaLogicalvolume object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseEtvaLogicalvolumePeer:doUpdate:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseEtvaLogicalvolumePeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(EtvaLogicalvolumePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(EtvaLogicalvolumePeer::ID);
			$selectCriteria->add(EtvaLogicalvolumePeer::ID, $criteria->remove(EtvaLogicalvolumePeer::ID), $comparison);

		} else { // $values is EtvaLogicalvolume object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);
	

    foreach (sfMixer::getCallables('BaseEtvaLogicalvolumePeer:doUpdate:post') as $callable)
    {
      call_user_func($callable, 'BaseEtvaLogicalvolumePeer', $values, $con, $ret);
    }

    return $ret;
  }

	/**
	 * Method to DELETE all rows from the logicalvolume table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(EtvaLogicalvolumePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(EtvaLogicalvolumePeer::TABLE_NAME, $con);
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a EtvaLogicalvolume or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or EtvaLogicalvolume object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(EtvaLogicalvolumePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			EtvaLogicalvolumePeer::clearInstancePool();

			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof EtvaLogicalvolume) {
			// invalidate the cache for this single object
			EtvaLogicalvolumePeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else {
			// it must be the primary key



			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(EtvaLogicalvolumePeer::ID, (array) $values, Criteria::IN);

			foreach ((array) $values as $singleval) {
				// we can invalidate the cache for this single object
				EtvaLogicalvolumePeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			$affectedRows += BasePeer::doDelete($criteria, $con);

			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given EtvaLogicalvolume object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      EtvaLogicalvolume $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(EtvaLogicalvolume $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(EtvaLogicalvolumePeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(EtvaLogicalvolumePeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		$res =  BasePeer::doValidate(EtvaLogicalvolumePeer::DATABASE_NAME, EtvaLogicalvolumePeer::TABLE_NAME, $columns);
    if ($res !== true) {
        $request = sfContext::getInstance()->getRequest();
        foreach ($res as $failed) {
            $col = EtvaLogicalvolumePeer::translateFieldname($failed->getColumn(), BasePeer::TYPE_COLNAME, BasePeer::TYPE_PHPNAME);
        }
    }

    return $res;
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     EtvaLogicalvolume
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = EtvaLogicalvolumePeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(EtvaLogicalvolumePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(EtvaLogicalvolumePeer::DATABASE_NAME);
		$criteria->add(EtvaLogicalvolumePeer::ID, $pk);

		$v = EtvaLogicalvolumePeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(EtvaLogicalvolumePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(EtvaLogicalvolumePeer::DATABASE_NAME);
			$criteria->add(EtvaLogicalvolumePeer::ID, $pks, Criteria::IN);
			$objs = EtvaLogicalvolumePeer::doSelect($criteria, $con);
		}
		return $objs;
	}

} // BaseEtvaLogicalvolumePeer

// This is the static code needed to register the MapBuilder for this table with the main Propel class.
//
// NOTE: This static code cannot call methods on the EtvaLogicalvolumePeer class, because it is not defined yet.
// If you need to use overridden methods, you can add this code to the bottom of the EtvaLogicalvolumePeer class:
//
// Propel::getDatabaseMap(EtvaLogicalvolumePeer::DATABASE_NAME)->addTableBuilder(EtvaLogicalvolumePeer::TABLE_NAME, EtvaLogicalvolumePeer::getMapBuilder());
//
// Doing so will effectively overwrite the registration below.

Propel::getDatabaseMap(BaseEtvaLogicalvolumePeer::DATABASE_NAME)->addTableBuilder(BaseEtvaLogicalvolumePeer::TABLE_NAME, BaseEtvaLogicalvolumePeer::getMapBuilder());

