<?php

/**
 * Base class that represents a row from the 'physicalvolume' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Fri Aug 28 18:22:07 2009
 *
 * @package    lib.model.om
 */
abstract class BaseEtvaPhysicalvolume extends BaseObject  implements Persistent {


  const PEER = 'EtvaPhysicalvolumePeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        EtvaPhysicalvolumePeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the node_id field.
	 * @var        int
	 */
	protected $node_id;

	/**
	 * The value for the name field.
	 * @var        string
	 */
	protected $name;

	/**
	 * The value for the device field.
	 * @var        string
	 */
	protected $device;

	/**
	 * The value for the devsize field.
	 * @var        string
	 */
	protected $devsize;

	/**
	 * The value for the pv field.
	 * @var        string
	 */
	protected $pv;

	/**
	 * The value for the pvsize field.
	 * @var        string
	 */
	protected $pvsize;

	/**
	 * The value for the pvfreesize field.
	 * @var        string
	 */
	protected $pvfreesize;

	/**
	 * The value for the pvinit field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $pvinit;

	/**
	 * The value for the storage_type field.
	 * @var        string
	 */
	protected $storage_type;

	/**
	 * The value for the allocatable field.
	 * @var        int
	 */
	protected $allocatable;

	/**
	 * @var        EtvaNode
	 */
	protected $aEtvaNode;

	/**
	 * @var        array EtvaVolumePhysical[] Collection to store aggregation of EtvaVolumePhysical objects.
	 */
	protected $collEtvaVolumePhysicals;

	/**
	 * @var        Criteria The criteria used to select the current contents of collEtvaVolumePhysicals.
	 */
	private $lastEtvaVolumePhysicalCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseEtvaPhysicalvolume object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->pvinit = 0;
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [node_id] column value.
	 * 
	 * @return     int
	 */
	public function getNodeId()
	{
		return $this->node_id;
	}

	/**
	 * Get the [name] column value.
	 * 
	 * @return     string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Get the [device] column value.
	 * 
	 * @return     string
	 */
	public function getDevice()
	{
		return $this->device;
	}

	/**
	 * Get the [devsize] column value.
	 * 
	 * @return     string
	 */
	public function getDevsize()
	{
		return $this->devsize;
	}

	/**
	 * Get the [pv] column value.
	 * 
	 * @return     string
	 */
	public function getPv()
	{
		return $this->pv;
	}

	/**
	 * Get the [pvsize] column value.
	 * 
	 * @return     string
	 */
	public function getPvsize()
	{
		return $this->pvsize;
	}

	/**
	 * Get the [pvfreesize] column value.
	 * 
	 * @return     string
	 */
	public function getPvfreesize()
	{
		return $this->pvfreesize;
	}

	/**
	 * Get the [pvinit] column value.
	 * 
	 * @return     int
	 */
	public function getPvinit()
	{
		return $this->pvinit;
	}

	/**
	 * Get the [storage_type] column value.
	 * 
	 * @return     string
	 */
	public function getStorageType()
	{
		return $this->storage_type;
	}

	/**
	 * Get the [allocatable] column value.
	 * 
	 * @return     int
	 */
	public function getAllocatable()
	{
		return $this->allocatable;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     EtvaPhysicalvolume The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = EtvaPhysicalvolumePeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [node_id] column.
	 * 
	 * @param      int $v new value
	 * @return     EtvaPhysicalvolume The current object (for fluent API support)
	 */
	public function setNodeId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->node_id !== $v) {
			$this->node_id = $v;
			$this->modifiedColumns[] = EtvaPhysicalvolumePeer::NODE_ID;
		}

		if ($this->aEtvaNode !== null && $this->aEtvaNode->getId() !== $v) {
			$this->aEtvaNode = null;
		}

		return $this;
	} // setNodeId()

	/**
	 * Set the value of [name] column.
	 * 
	 * @param      string $v new value
	 * @return     EtvaPhysicalvolume The current object (for fluent API support)
	 */
	public function setName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->name !== $v) {
			$this->name = $v;
			$this->modifiedColumns[] = EtvaPhysicalvolumePeer::NAME;
		}

		return $this;
	} // setName()

	/**
	 * Set the value of [device] column.
	 * 
	 * @param      string $v new value
	 * @return     EtvaPhysicalvolume The current object (for fluent API support)
	 */
	public function setDevice($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->device !== $v) {
			$this->device = $v;
			$this->modifiedColumns[] = EtvaPhysicalvolumePeer::DEVICE;
		}

		return $this;
	} // setDevice()

	/**
	 * Set the value of [devsize] column.
	 * 
	 * @param      string $v new value
	 * @return     EtvaPhysicalvolume The current object (for fluent API support)
	 */
	public function setDevsize($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->devsize !== $v) {
			$this->devsize = $v;
			$this->modifiedColumns[] = EtvaPhysicalvolumePeer::DEVSIZE;
		}

		return $this;
	} // setDevsize()

	/**
	 * Set the value of [pv] column.
	 * 
	 * @param      string $v new value
	 * @return     EtvaPhysicalvolume The current object (for fluent API support)
	 */
	public function setPv($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->pv !== $v) {
			$this->pv = $v;
			$this->modifiedColumns[] = EtvaPhysicalvolumePeer::PV;
		}

		return $this;
	} // setPv()

	/**
	 * Set the value of [pvsize] column.
	 * 
	 * @param      string $v new value
	 * @return     EtvaPhysicalvolume The current object (for fluent API support)
	 */
	public function setPvsize($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->pvsize !== $v) {
			$this->pvsize = $v;
			$this->modifiedColumns[] = EtvaPhysicalvolumePeer::PVSIZE;
		}

		return $this;
	} // setPvsize()

	/**
	 * Set the value of [pvfreesize] column.
	 * 
	 * @param      string $v new value
	 * @return     EtvaPhysicalvolume The current object (for fluent API support)
	 */
	public function setPvfreesize($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->pvfreesize !== $v) {
			$this->pvfreesize = $v;
			$this->modifiedColumns[] = EtvaPhysicalvolumePeer::PVFREESIZE;
		}

		return $this;
	} // setPvfreesize()

	/**
	 * Set the value of [pvinit] column.
	 * 
	 * @param      int $v new value
	 * @return     EtvaPhysicalvolume The current object (for fluent API support)
	 */
	public function setPvinit($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->pvinit !== $v || $v === 0) {
			$this->pvinit = $v;
			$this->modifiedColumns[] = EtvaPhysicalvolumePeer::PVINIT;
		}

		return $this;
	} // setPvinit()

	/**
	 * Set the value of [storage_type] column.
	 * 
	 * @param      string $v new value
	 * @return     EtvaPhysicalvolume The current object (for fluent API support)
	 */
	public function setStorageType($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->storage_type !== $v) {
			$this->storage_type = $v;
			$this->modifiedColumns[] = EtvaPhysicalvolumePeer::STORAGE_TYPE;
		}

		return $this;
	} // setStorageType()

	/**
	 * Set the value of [allocatable] column.
	 * 
	 * @param      int $v new value
	 * @return     EtvaPhysicalvolume The current object (for fluent API support)
	 */
	public function setAllocatable($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->allocatable !== $v) {
			$this->allocatable = $v;
			$this->modifiedColumns[] = EtvaPhysicalvolumePeer::ALLOCATABLE;
		}

		return $this;
	} // setAllocatable()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array(EtvaPhysicalvolumePeer::PVINIT))) {
				return false;
			}

			if ($this->pvinit !== 0) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->node_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->name = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->device = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->devsize = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->pv = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->pvsize = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->pvfreesize = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->pvinit = ($row[$startcol + 8] !== null) ? (int) $row[$startcol + 8] : null;
			$this->storage_type = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->allocatable = ($row[$startcol + 10] !== null) ? (int) $row[$startcol + 10] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 11; // 11 = EtvaPhysicalvolumePeer::NUM_COLUMNS - EtvaPhysicalvolumePeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating EtvaPhysicalvolume object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aEtvaNode !== null && $this->node_id !== $this->aEtvaNode->getId()) {
			$this->aEtvaNode = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(EtvaPhysicalvolumePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = EtvaPhysicalvolumePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aEtvaNode = null;
			$this->collEtvaVolumePhysicals = null;
			$this->lastEtvaVolumePhysicalCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseEtvaPhysicalvolume:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(EtvaPhysicalvolumePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			EtvaPhysicalvolumePeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseEtvaPhysicalvolume:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseEtvaPhysicalvolume:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(EtvaPhysicalvolumePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseEtvaPhysicalvolume:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			EtvaPhysicalvolumePeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aEtvaNode !== null) {
				if ($this->aEtvaNode->isModified() || $this->aEtvaNode->isNew()) {
					$affectedRows += $this->aEtvaNode->save($con);
				}
				$this->setEtvaNode($this->aEtvaNode);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = EtvaPhysicalvolumePeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = EtvaPhysicalvolumePeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += EtvaPhysicalvolumePeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collEtvaVolumePhysicals !== null) {
				foreach ($this->collEtvaVolumePhysicals as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aEtvaNode !== null) {
				if (!$this->aEtvaNode->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aEtvaNode->getValidationFailures());
				}
			}


			if (($retval = EtvaPhysicalvolumePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collEtvaVolumePhysicals !== null) {
					foreach ($this->collEtvaVolumePhysicals as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = EtvaPhysicalvolumePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getNodeId();
				break;
			case 2:
				return $this->getName();
				break;
			case 3:
				return $this->getDevice();
				break;
			case 4:
				return $this->getDevsize();
				break;
			case 5:
				return $this->getPv();
				break;
			case 6:
				return $this->getPvsize();
				break;
			case 7:
				return $this->getPvfreesize();
				break;
			case 8:
				return $this->getPvinit();
				break;
			case 9:
				return $this->getStorageType();
				break;
			case 10:
				return $this->getAllocatable();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = EtvaPhysicalvolumePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getNodeId(),
			$keys[2] => $this->getName(),
			$keys[3] => $this->getDevice(),
			$keys[4] => $this->getDevsize(),
			$keys[5] => $this->getPv(),
			$keys[6] => $this->getPvsize(),
			$keys[7] => $this->getPvfreesize(),
			$keys[8] => $this->getPvinit(),
			$keys[9] => $this->getStorageType(),
			$keys[10] => $this->getAllocatable(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = EtvaPhysicalvolumePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setNodeId($value);
				break;
			case 2:
				$this->setName($value);
				break;
			case 3:
				$this->setDevice($value);
				break;
			case 4:
				$this->setDevsize($value);
				break;
			case 5:
				$this->setPv($value);
				break;
			case 6:
				$this->setPvsize($value);
				break;
			case 7:
				$this->setPvfreesize($value);
				break;
			case 8:
				$this->setPvinit($value);
				break;
			case 9:
				$this->setStorageType($value);
				break;
			case 10:
				$this->setAllocatable($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = EtvaPhysicalvolumePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setNodeId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setName($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setDevice($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setDevsize($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setPv($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setPvsize($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setPvfreesize($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setPvinit($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setStorageType($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setAllocatable($arr[$keys[10]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(EtvaPhysicalvolumePeer::DATABASE_NAME);

		if ($this->isColumnModified(EtvaPhysicalvolumePeer::ID)) $criteria->add(EtvaPhysicalvolumePeer::ID, $this->id);
		if ($this->isColumnModified(EtvaPhysicalvolumePeer::NODE_ID)) $criteria->add(EtvaPhysicalvolumePeer::NODE_ID, $this->node_id);
		if ($this->isColumnModified(EtvaPhysicalvolumePeer::NAME)) $criteria->add(EtvaPhysicalvolumePeer::NAME, $this->name);
		if ($this->isColumnModified(EtvaPhysicalvolumePeer::DEVICE)) $criteria->add(EtvaPhysicalvolumePeer::DEVICE, $this->device);
		if ($this->isColumnModified(EtvaPhysicalvolumePeer::DEVSIZE)) $criteria->add(EtvaPhysicalvolumePeer::DEVSIZE, $this->devsize);
		if ($this->isColumnModified(EtvaPhysicalvolumePeer::PV)) $criteria->add(EtvaPhysicalvolumePeer::PV, $this->pv);
		if ($this->isColumnModified(EtvaPhysicalvolumePeer::PVSIZE)) $criteria->add(EtvaPhysicalvolumePeer::PVSIZE, $this->pvsize);
		if ($this->isColumnModified(EtvaPhysicalvolumePeer::PVFREESIZE)) $criteria->add(EtvaPhysicalvolumePeer::PVFREESIZE, $this->pvfreesize);
		if ($this->isColumnModified(EtvaPhysicalvolumePeer::PVINIT)) $criteria->add(EtvaPhysicalvolumePeer::PVINIT, $this->pvinit);
		if ($this->isColumnModified(EtvaPhysicalvolumePeer::STORAGE_TYPE)) $criteria->add(EtvaPhysicalvolumePeer::STORAGE_TYPE, $this->storage_type);
		if ($this->isColumnModified(EtvaPhysicalvolumePeer::ALLOCATABLE)) $criteria->add(EtvaPhysicalvolumePeer::ALLOCATABLE, $this->allocatable);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(EtvaPhysicalvolumePeer::DATABASE_NAME);

		$criteria->add(EtvaPhysicalvolumePeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of EtvaPhysicalvolume (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setNodeId($this->node_id);

		$copyObj->setName($this->name);

		$copyObj->setDevice($this->device);

		$copyObj->setDevsize($this->devsize);

		$copyObj->setPv($this->pv);

		$copyObj->setPvsize($this->pvsize);

		$copyObj->setPvfreesize($this->pvfreesize);

		$copyObj->setPvinit($this->pvinit);

		$copyObj->setStorageType($this->storage_type);

		$copyObj->setAllocatable($this->allocatable);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getEtvaVolumePhysicals() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addEtvaVolumePhysical($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     EtvaPhysicalvolume Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     EtvaPhysicalvolumePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new EtvaPhysicalvolumePeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a EtvaNode object.
	 *
	 * @param      EtvaNode $v
	 * @return     EtvaPhysicalvolume The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setEtvaNode(EtvaNode $v = null)
	{
		if ($v === null) {
			$this->setNodeId(NULL);
		} else {
			$this->setNodeId($v->getId());
		}

		$this->aEtvaNode = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the EtvaNode object, it will not be re-added.
		if ($v !== null) {
			$v->addEtvaPhysicalvolume($this);
		}

		return $this;
	}


	/**
	 * Get the associated EtvaNode object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     EtvaNode The associated EtvaNode object.
	 * @throws     PropelException
	 */
	public function getEtvaNode(PropelPDO $con = null)
	{
		if ($this->aEtvaNode === null && ($this->node_id !== null)) {
			$c = new Criteria(EtvaNodePeer::DATABASE_NAME);
			$c->add(EtvaNodePeer::ID, $this->node_id);
			$this->aEtvaNode = EtvaNodePeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aEtvaNode->addEtvaPhysicalvolumes($this);
			 */
		}
		return $this->aEtvaNode;
	}

	/**
	 * Clears out the collEtvaVolumePhysicals collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addEtvaVolumePhysicals()
	 */
	public function clearEtvaVolumePhysicals()
	{
		$this->collEtvaVolumePhysicals = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collEtvaVolumePhysicals collection (array).
	 *
	 * By default this just sets the collEtvaVolumePhysicals collection to an empty array (like clearcollEtvaVolumePhysicals());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initEtvaVolumePhysicals()
	{
		$this->collEtvaVolumePhysicals = array();
	}

	/**
	 * Gets an array of EtvaVolumePhysical objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this EtvaPhysicalvolume has previously been saved, it will retrieve
	 * related EtvaVolumePhysicals from storage. If this EtvaPhysicalvolume is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array EtvaVolumePhysical[]
	 * @throws     PropelException
	 */
	public function getEtvaVolumePhysicals($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EtvaPhysicalvolumePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collEtvaVolumePhysicals === null) {
			if ($this->isNew()) {
			   $this->collEtvaVolumePhysicals = array();
			} else {

				$criteria->add(EtvaVolumePhysicalPeer::PHYSICALVOLUME_ID, $this->id);

				EtvaVolumePhysicalPeer::addSelectColumns($criteria);
				$this->collEtvaVolumePhysicals = EtvaVolumePhysicalPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(EtvaVolumePhysicalPeer::PHYSICALVOLUME_ID, $this->id);

				EtvaVolumePhysicalPeer::addSelectColumns($criteria);
				if (!isset($this->lastEtvaVolumePhysicalCriteria) || !$this->lastEtvaVolumePhysicalCriteria->equals($criteria)) {
					$this->collEtvaVolumePhysicals = EtvaVolumePhysicalPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastEtvaVolumePhysicalCriteria = $criteria;
		return $this->collEtvaVolumePhysicals;
	}

	/**
	 * Returns the number of related EtvaVolumePhysical objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related EtvaVolumePhysical objects.
	 * @throws     PropelException
	 */
	public function countEtvaVolumePhysicals(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EtvaPhysicalvolumePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collEtvaVolumePhysicals === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(EtvaVolumePhysicalPeer::PHYSICALVOLUME_ID, $this->id);

				$count = EtvaVolumePhysicalPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(EtvaVolumePhysicalPeer::PHYSICALVOLUME_ID, $this->id);

				if (!isset($this->lastEtvaVolumePhysicalCriteria) || !$this->lastEtvaVolumePhysicalCriteria->equals($criteria)) {
					$count = EtvaVolumePhysicalPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collEtvaVolumePhysicals);
				}
			} else {
				$count = count($this->collEtvaVolumePhysicals);
			}
		}
		$this->lastEtvaVolumePhysicalCriteria = $criteria;
		return $count;
	}

	/**
	 * Method called to associate a EtvaVolumePhysical object to this object
	 * through the EtvaVolumePhysical foreign key attribute.
	 *
	 * @param      EtvaVolumePhysical $l EtvaVolumePhysical
	 * @return     void
	 * @throws     PropelException
	 */
	public function addEtvaVolumePhysical(EtvaVolumePhysical $l)
	{
		if ($this->collEtvaVolumePhysicals === null) {
			$this->initEtvaVolumePhysicals();
		}
		if (!in_array($l, $this->collEtvaVolumePhysicals, true)) { // only add it if the **same** object is not already associated
			array_push($this->collEtvaVolumePhysicals, $l);
			$l->setEtvaPhysicalvolume($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this EtvaPhysicalvolume is new, it will return
	 * an empty collection; or if this EtvaPhysicalvolume has previously
	 * been saved, it will retrieve related EtvaVolumePhysicals from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in EtvaPhysicalvolume.
	 */
	public function getEtvaVolumePhysicalsJoinEtvaVolumegroup($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EtvaPhysicalvolumePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collEtvaVolumePhysicals === null) {
			if ($this->isNew()) {
				$this->collEtvaVolumePhysicals = array();
			} else {

				$criteria->add(EtvaVolumePhysicalPeer::PHYSICALVOLUME_ID, $this->id);

				$this->collEtvaVolumePhysicals = EtvaVolumePhysicalPeer::doSelectJoinEtvaVolumegroup($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(EtvaVolumePhysicalPeer::PHYSICALVOLUME_ID, $this->id);

			if (!isset($this->lastEtvaVolumePhysicalCriteria) || !$this->lastEtvaVolumePhysicalCriteria->equals($criteria)) {
				$this->collEtvaVolumePhysicals = EtvaVolumePhysicalPeer::doSelectJoinEtvaVolumegroup($criteria, $con, $join_behavior);
			}
		}
		$this->lastEtvaVolumePhysicalCriteria = $criteria;

		return $this->collEtvaVolumePhysicals;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collEtvaVolumePhysicals) {
				foreach ((array) $this->collEtvaVolumePhysicals as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collEtvaVolumePhysicals = null;
			$this->aEtvaNode = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseEtvaPhysicalvolume:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseEtvaPhysicalvolume::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseEtvaPhysicalvolume
