<?php

/**
 * Base static class for performing query and update operations on the 'server' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Fri Aug 28 18:22:07 2009
 *
 * @package    lib.model.om
 */
abstract class BaseEtvaServerPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'server';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.EtvaServer';

	/** The total number of columns. */
	const NUM_COLUMNS = 20;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the ID field */
	const ID = 'server.ID';

	/** the column name for the LOGICALVOLUME_ID field */
	const LOGICALVOLUME_ID = 'server.LOGICALVOLUME_ID';

	/** the column name for the NODE_ID field */
	const NODE_ID = 'server.NODE_ID';

	/** the column name for the NAME field */
	const NAME = 'server.NAME';

	/** the column name for the DESCRIPTION field */
	const DESCRIPTION = 'server.DESCRIPTION';

	/** the column name for the IP field */
	const IP = 'server.IP';

	/** the column name for the VNC_PORT field */
	const VNC_PORT = 'server.VNC_PORT';

	/** the column name for the AGENT_PORT field */
	const AGENT_PORT = 'server.AGENT_PORT';

	/** the column name for the AGENT_TMPL field */
	const AGENT_TMPL = 'server.AGENT_TMPL';

	/** the column name for the UID field */
	const UID = 'server.UID';

	/** the column name for the MEM field */
	const MEM = 'server.MEM';

	/** the column name for the VCPU field */
	const VCPU = 'server.VCPU';

	/** the column name for the CPUSET field */
	const CPUSET = 'server.CPUSET';

	/** the column name for the LOCATION field */
	const LOCATION = 'server.LOCATION';

	/** the column name for the NETWORK_CARDS field */
	const NETWORK_CARDS = 'server.NETWORK_CARDS';

	/** the column name for the STATE field */
	const STATE = 'server.STATE';

	/** the column name for the MAC_ADDRESSES field */
	const MAC_ADDRESSES = 'server.MAC_ADDRESSES';

	/** the column name for the SF_GUARD_GROUP_ID field */
	const SF_GUARD_GROUP_ID = 'server.SF_GUARD_GROUP_ID';

	/** the column name for the CREATED_AT field */
	const CREATED_AT = 'server.CREATED_AT';

	/** the column name for the UPDATED_AT field */
	const UPDATED_AT = 'server.UPDATED_AT';

	/**
	 * An identiy map to hold any loaded instances of EtvaServer objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array EtvaServer[]
	 */
	public static $instances = array();

	/**
	 * The MapBuilder instance for this peer.
	 * @var        MapBuilder
	 */
	private static $mapBuilder = null;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('Id', 'LogicalvolumeId', 'NodeId', 'Name', 'Description', 'Ip', 'VncPort', 'AgentPort', 'AgentTmpl', 'Uid', 'Mem', 'Vcpu', 'Cpuset', 'Location', 'NetworkCards', 'State', 'MacAddresses', 'SfGuardGroupId', 'CreatedAt', 'UpdatedAt', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id', 'logicalvolumeId', 'nodeId', 'name', 'description', 'ip', 'vncPort', 'agentPort', 'agentTmpl', 'uid', 'mem', 'vcpu', 'cpuset', 'location', 'networkCards', 'state', 'macAddresses', 'sfGuardGroupId', 'createdAt', 'updatedAt', ),
		BasePeer::TYPE_COLNAME => array (self::ID, self::LOGICALVOLUME_ID, self::NODE_ID, self::NAME, self::DESCRIPTION, self::IP, self::VNC_PORT, self::AGENT_PORT, self::AGENT_TMPL, self::UID, self::MEM, self::VCPU, self::CPUSET, self::LOCATION, self::NETWORK_CARDS, self::STATE, self::MAC_ADDRESSES, self::SF_GUARD_GROUP_ID, self::CREATED_AT, self::UPDATED_AT, ),
		BasePeer::TYPE_FIELDNAME => array ('id', 'logicalvolume_id', 'node_id', 'name', 'description', 'ip', 'vnc_port', 'agent_port', 'agent_tmpl', 'uid', 'mem', 'vcpu', 'cpuset', 'location', 'network_cards', 'state', 'mac_addresses', 'sf_guard_group_id', 'created_at', 'updated_at', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('Id' => 0, 'LogicalvolumeId' => 1, 'NodeId' => 2, 'Name' => 3, 'Description' => 4, 'Ip' => 5, 'VncPort' => 6, 'AgentPort' => 7, 'AgentTmpl' => 8, 'Uid' => 9, 'Mem' => 10, 'Vcpu' => 11, 'Cpuset' => 12, 'Location' => 13, 'NetworkCards' => 14, 'State' => 15, 'MacAddresses' => 16, 'SfGuardGroupId' => 17, 'CreatedAt' => 18, 'UpdatedAt' => 19, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id' => 0, 'logicalvolumeId' => 1, 'nodeId' => 2, 'name' => 3, 'description' => 4, 'ip' => 5, 'vncPort' => 6, 'agentPort' => 7, 'agentTmpl' => 8, 'uid' => 9, 'mem' => 10, 'vcpu' => 11, 'cpuset' => 12, 'location' => 13, 'networkCards' => 14, 'state' => 15, 'macAddresses' => 16, 'sfGuardGroupId' => 17, 'createdAt' => 18, 'updatedAt' => 19, ),
		BasePeer::TYPE_COLNAME => array (self::ID => 0, self::LOGICALVOLUME_ID => 1, self::NODE_ID => 2, self::NAME => 3, self::DESCRIPTION => 4, self::IP => 5, self::VNC_PORT => 6, self::AGENT_PORT => 7, self::AGENT_TMPL => 8, self::UID => 9, self::MEM => 10, self::VCPU => 11, self::CPUSET => 12, self::LOCATION => 13, self::NETWORK_CARDS => 14, self::STATE => 15, self::MAC_ADDRESSES => 16, self::SF_GUARD_GROUP_ID => 17, self::CREATED_AT => 18, self::UPDATED_AT => 19, ),
		BasePeer::TYPE_FIELDNAME => array ('id' => 0, 'logicalvolume_id' => 1, 'node_id' => 2, 'name' => 3, 'description' => 4, 'ip' => 5, 'vnc_port' => 6, 'agent_port' => 7, 'agent_tmpl' => 8, 'uid' => 9, 'mem' => 10, 'vcpu' => 11, 'cpuset' => 12, 'location' => 13, 'network_cards' => 14, 'state' => 15, 'mac_addresses' => 16, 'sf_guard_group_id' => 17, 'created_at' => 18, 'updated_at' => 19, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, )
	);

	/**
	 * Get a (singleton) instance of the MapBuilder for this peer class.
	 * @return     MapBuilder The map builder for this peer
	 */
	public static function getMapBuilder()
	{
		if (self::$mapBuilder === null) {
			self::$mapBuilder = new EtvaServerMapBuilder();
		}
		return self::$mapBuilder;
	}
	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. EtvaServerPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(EtvaServerPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{

		$criteria->addSelectColumn(EtvaServerPeer::ID);

		$criteria->addSelectColumn(EtvaServerPeer::LOGICALVOLUME_ID);

		$criteria->addSelectColumn(EtvaServerPeer::NODE_ID);

		$criteria->addSelectColumn(EtvaServerPeer::NAME);

		$criteria->addSelectColumn(EtvaServerPeer::DESCRIPTION);

		$criteria->addSelectColumn(EtvaServerPeer::IP);

		$criteria->addSelectColumn(EtvaServerPeer::VNC_PORT);

		$criteria->addSelectColumn(EtvaServerPeer::AGENT_PORT);

		$criteria->addSelectColumn(EtvaServerPeer::AGENT_TMPL);

		$criteria->addSelectColumn(EtvaServerPeer::UID);

		$criteria->addSelectColumn(EtvaServerPeer::MEM);

		$criteria->addSelectColumn(EtvaServerPeer::VCPU);

		$criteria->addSelectColumn(EtvaServerPeer::CPUSET);

		$criteria->addSelectColumn(EtvaServerPeer::LOCATION);

		$criteria->addSelectColumn(EtvaServerPeer::NETWORK_CARDS);

		$criteria->addSelectColumn(EtvaServerPeer::STATE);

		$criteria->addSelectColumn(EtvaServerPeer::MAC_ADDRESSES);

		$criteria->addSelectColumn(EtvaServerPeer::SF_GUARD_GROUP_ID);

		$criteria->addSelectColumn(EtvaServerPeer::CREATED_AT);

		$criteria->addSelectColumn(EtvaServerPeer::UPDATED_AT);

	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(EtvaServerPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			EtvaServerPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(EtvaServerPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}


    foreach (sfMixer::getCallables('BaseEtvaServerPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseEtvaServerPeer', $criteria, $con);
    }


		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     EtvaServer
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = EtvaServerPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return EtvaServerPeer::populateObjects(EtvaServerPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseEtvaServerPeer:doSelectStmt:doSelectStmt') as $callable)
    {
      call_user_func($callable, 'BaseEtvaServerPeer', $criteria, $con);
    }


		if ($con === null) {
			$con = Propel::getConnection(EtvaServerPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			EtvaServerPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      EtvaServer $value A EtvaServer object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(EtvaServer $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getId();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A EtvaServer object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof EtvaServer) {
				$key = (string) $value->getId();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or EtvaServer object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     EtvaServer Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol + 0] === null) {
			return null;
		}
		return (string) $row[$startcol + 0];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = EtvaServerPeer::getOMClass();
		$cls = substr('.'.$cls, strrpos('.'.$cls, '.') + 1);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = EtvaServerPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = EtvaServerPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
		
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				EtvaServerPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}

	/**
	 * Returns the number of rows matching criteria, joining the related EtvaLogicalvolume table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinEtvaLogicalvolume(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(EtvaServerPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			EtvaServerPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(EtvaServerPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(EtvaServerPeer::LOGICALVOLUME_ID,), array(EtvaLogicalvolumePeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseEtvaServerPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseEtvaServerPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related EtvaNode table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinEtvaNode(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(EtvaServerPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			EtvaServerPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(EtvaServerPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(EtvaServerPeer::NODE_ID,), array(EtvaNodePeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseEtvaServerPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseEtvaServerPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related sfGuardGroup table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinsfGuardGroup(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(EtvaServerPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			EtvaServerPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(EtvaServerPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(EtvaServerPeer::SF_GUARD_GROUP_ID,), array(sfGuardGroupPeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseEtvaServerPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseEtvaServerPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of EtvaServer objects pre-filled with their EtvaLogicalvolume objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of EtvaServer objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinEtvaLogicalvolume(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseEtvaServerPeer:doSelectJoin:doSelectJoin') as $callable)
    {
      call_user_func($callable, 'BaseEtvaServerPeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		EtvaServerPeer::addSelectColumns($c);
		$startcol = (EtvaServerPeer::NUM_COLUMNS - EtvaServerPeer::NUM_LAZY_LOAD_COLUMNS);
		EtvaLogicalvolumePeer::addSelectColumns($c);

		$c->addJoin(array(EtvaServerPeer::LOGICALVOLUME_ID,), array(EtvaLogicalvolumePeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = EtvaServerPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = EtvaServerPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = EtvaServerPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				EtvaServerPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = EtvaLogicalvolumePeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = EtvaLogicalvolumePeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = EtvaLogicalvolumePeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					EtvaLogicalvolumePeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (EtvaServer) to $obj2 (EtvaLogicalvolume)
				$obj2->addEtvaServer($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of EtvaServer objects pre-filled with their EtvaNode objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of EtvaServer objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinEtvaNode(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		EtvaServerPeer::addSelectColumns($c);
		$startcol = (EtvaServerPeer::NUM_COLUMNS - EtvaServerPeer::NUM_LAZY_LOAD_COLUMNS);
		EtvaNodePeer::addSelectColumns($c);

		$c->addJoin(array(EtvaServerPeer::NODE_ID,), array(EtvaNodePeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = EtvaServerPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = EtvaServerPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = EtvaServerPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				EtvaServerPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = EtvaNodePeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = EtvaNodePeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = EtvaNodePeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					EtvaNodePeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (EtvaServer) to $obj2 (EtvaNode)
				$obj2->addEtvaServer($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of EtvaServer objects pre-filled with their sfGuardGroup objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of EtvaServer objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinsfGuardGroup(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		EtvaServerPeer::addSelectColumns($c);
		$startcol = (EtvaServerPeer::NUM_COLUMNS - EtvaServerPeer::NUM_LAZY_LOAD_COLUMNS);
		sfGuardGroupPeer::addSelectColumns($c);

		$c->addJoin(array(EtvaServerPeer::SF_GUARD_GROUP_ID,), array(sfGuardGroupPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = EtvaServerPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = EtvaServerPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = EtvaServerPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				EtvaServerPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = sfGuardGroupPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = sfGuardGroupPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = sfGuardGroupPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					sfGuardGroupPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (EtvaServer) to $obj2 (sfGuardGroup)
				$obj2->addEtvaServer($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining all related tables
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAll(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(EtvaServerPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			EtvaServerPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(EtvaServerPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(EtvaServerPeer::LOGICALVOLUME_ID,), array(EtvaLogicalvolumePeer::ID,), $join_behavior);
		$criteria->addJoin(array(EtvaServerPeer::NODE_ID,), array(EtvaNodePeer::ID,), $join_behavior);
		$criteria->addJoin(array(EtvaServerPeer::SF_GUARD_GROUP_ID,), array(sfGuardGroupPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseEtvaServerPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseEtvaServerPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}

	/**
	 * Selects a collection of EtvaServer objects pre-filled with all related objects.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of EtvaServer objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAll(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseEtvaServerPeer:doSelectJoinAll:doSelectJoinAll') as $callable)
    {
      call_user_func($callable, 'BaseEtvaServerPeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		EtvaServerPeer::addSelectColumns($c);
		$startcol2 = (EtvaServerPeer::NUM_COLUMNS - EtvaServerPeer::NUM_LAZY_LOAD_COLUMNS);

		EtvaLogicalvolumePeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (EtvaLogicalvolumePeer::NUM_COLUMNS - EtvaLogicalvolumePeer::NUM_LAZY_LOAD_COLUMNS);

		EtvaNodePeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (EtvaNodePeer::NUM_COLUMNS - EtvaNodePeer::NUM_LAZY_LOAD_COLUMNS);

		sfGuardGroupPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (sfGuardGroupPeer::NUM_COLUMNS - sfGuardGroupPeer::NUM_LAZY_LOAD_COLUMNS);

		$c->addJoin(array(EtvaServerPeer::LOGICALVOLUME_ID,), array(EtvaLogicalvolumePeer::ID,), $join_behavior);
		$c->addJoin(array(EtvaServerPeer::NODE_ID,), array(EtvaNodePeer::ID,), $join_behavior);
		$c->addJoin(array(EtvaServerPeer::SF_GUARD_GROUP_ID,), array(sfGuardGroupPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = EtvaServerPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = EtvaServerPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = EtvaServerPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				EtvaServerPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

			// Add objects for joined EtvaLogicalvolume rows

			$key2 = EtvaLogicalvolumePeer::getPrimaryKeyHashFromRow($row, $startcol2);
			if ($key2 !== null) {
				$obj2 = EtvaLogicalvolumePeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = EtvaLogicalvolumePeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					EtvaLogicalvolumePeer::addInstanceToPool($obj2, $key2);
				} // if obj2 loaded

				// Add the $obj1 (EtvaServer) to the collection in $obj2 (EtvaLogicalvolume)
				$obj2->addEtvaServer($obj1);
			} // if joined row not null

			// Add objects for joined EtvaNode rows

			$key3 = EtvaNodePeer::getPrimaryKeyHashFromRow($row, $startcol3);
			if ($key3 !== null) {
				$obj3 = EtvaNodePeer::getInstanceFromPool($key3);
				if (!$obj3) {

					$omClass = EtvaNodePeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					EtvaNodePeer::addInstanceToPool($obj3, $key3);
				} // if obj3 loaded

				// Add the $obj1 (EtvaServer) to the collection in $obj3 (EtvaNode)
				$obj3->addEtvaServer($obj1);
			} // if joined row not null

			// Add objects for joined sfGuardGroup rows

			$key4 = sfGuardGroupPeer::getPrimaryKeyHashFromRow($row, $startcol4);
			if ($key4 !== null) {
				$obj4 = sfGuardGroupPeer::getInstanceFromPool($key4);
				if (!$obj4) {

					$omClass = sfGuardGroupPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					sfGuardGroupPeer::addInstanceToPool($obj4, $key4);
				} // if obj4 loaded

				// Add the $obj1 (EtvaServer) to the collection in $obj4 (sfGuardGroup)
				$obj4->addEtvaServer($obj1);
			} // if joined row not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related EtvaLogicalvolume table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptEtvaLogicalvolume(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			EtvaServerPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(EtvaServerPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(EtvaServerPeer::NODE_ID,), array(EtvaNodePeer::ID,), $join_behavior);
				$criteria->addJoin(array(EtvaServerPeer::SF_GUARD_GROUP_ID,), array(sfGuardGroupPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseEtvaServerPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseEtvaServerPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related EtvaNode table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptEtvaNode(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			EtvaServerPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(EtvaServerPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(EtvaServerPeer::LOGICALVOLUME_ID,), array(EtvaLogicalvolumePeer::ID,), $join_behavior);
				$criteria->addJoin(array(EtvaServerPeer::SF_GUARD_GROUP_ID,), array(sfGuardGroupPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseEtvaServerPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseEtvaServerPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related sfGuardGroup table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptsfGuardGroup(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			EtvaServerPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(EtvaServerPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(EtvaServerPeer::LOGICALVOLUME_ID,), array(EtvaLogicalvolumePeer::ID,), $join_behavior);
				$criteria->addJoin(array(EtvaServerPeer::NODE_ID,), array(EtvaNodePeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseEtvaServerPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseEtvaServerPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of EtvaServer objects pre-filled with all related objects except EtvaLogicalvolume.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of EtvaServer objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptEtvaLogicalvolume(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseEtvaServerPeer:doSelectJoinAllExcept:doSelectJoinAllExcept') as $callable)
    {
      call_user_func($callable, 'BaseEtvaServerPeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		EtvaServerPeer::addSelectColumns($c);
		$startcol2 = (EtvaServerPeer::NUM_COLUMNS - EtvaServerPeer::NUM_LAZY_LOAD_COLUMNS);

		EtvaNodePeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (EtvaNodePeer::NUM_COLUMNS - EtvaNodePeer::NUM_LAZY_LOAD_COLUMNS);

		sfGuardGroupPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (sfGuardGroupPeer::NUM_COLUMNS - sfGuardGroupPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(EtvaServerPeer::NODE_ID,), array(EtvaNodePeer::ID,), $join_behavior);
				$c->addJoin(array(EtvaServerPeer::SF_GUARD_GROUP_ID,), array(sfGuardGroupPeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = EtvaServerPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = EtvaServerPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = EtvaServerPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				EtvaServerPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined EtvaNode rows

				$key2 = EtvaNodePeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = EtvaNodePeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = EtvaNodePeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					EtvaNodePeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (EtvaServer) to the collection in $obj2 (EtvaNode)
				$obj2->addEtvaServer($obj1);

			} // if joined row is not null

				// Add objects for joined sfGuardGroup rows

				$key3 = sfGuardGroupPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = sfGuardGroupPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = sfGuardGroupPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					sfGuardGroupPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (EtvaServer) to the collection in $obj3 (sfGuardGroup)
				$obj3->addEtvaServer($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of EtvaServer objects pre-filled with all related objects except EtvaNode.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of EtvaServer objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptEtvaNode(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		EtvaServerPeer::addSelectColumns($c);
		$startcol2 = (EtvaServerPeer::NUM_COLUMNS - EtvaServerPeer::NUM_LAZY_LOAD_COLUMNS);

		EtvaLogicalvolumePeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (EtvaLogicalvolumePeer::NUM_COLUMNS - EtvaLogicalvolumePeer::NUM_LAZY_LOAD_COLUMNS);

		sfGuardGroupPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (sfGuardGroupPeer::NUM_COLUMNS - sfGuardGroupPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(EtvaServerPeer::LOGICALVOLUME_ID,), array(EtvaLogicalvolumePeer::ID,), $join_behavior);
				$c->addJoin(array(EtvaServerPeer::SF_GUARD_GROUP_ID,), array(sfGuardGroupPeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = EtvaServerPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = EtvaServerPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = EtvaServerPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				EtvaServerPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined EtvaLogicalvolume rows

				$key2 = EtvaLogicalvolumePeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = EtvaLogicalvolumePeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = EtvaLogicalvolumePeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					EtvaLogicalvolumePeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (EtvaServer) to the collection in $obj2 (EtvaLogicalvolume)
				$obj2->addEtvaServer($obj1);

			} // if joined row is not null

				// Add objects for joined sfGuardGroup rows

				$key3 = sfGuardGroupPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = sfGuardGroupPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = sfGuardGroupPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					sfGuardGroupPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (EtvaServer) to the collection in $obj3 (sfGuardGroup)
				$obj3->addEtvaServer($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of EtvaServer objects pre-filled with all related objects except sfGuardGroup.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of EtvaServer objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptsfGuardGroup(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		EtvaServerPeer::addSelectColumns($c);
		$startcol2 = (EtvaServerPeer::NUM_COLUMNS - EtvaServerPeer::NUM_LAZY_LOAD_COLUMNS);

		EtvaLogicalvolumePeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (EtvaLogicalvolumePeer::NUM_COLUMNS - EtvaLogicalvolumePeer::NUM_LAZY_LOAD_COLUMNS);

		EtvaNodePeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (EtvaNodePeer::NUM_COLUMNS - EtvaNodePeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(EtvaServerPeer::LOGICALVOLUME_ID,), array(EtvaLogicalvolumePeer::ID,), $join_behavior);
				$c->addJoin(array(EtvaServerPeer::NODE_ID,), array(EtvaNodePeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = EtvaServerPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = EtvaServerPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = EtvaServerPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				EtvaServerPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined EtvaLogicalvolume rows

				$key2 = EtvaLogicalvolumePeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = EtvaLogicalvolumePeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = EtvaLogicalvolumePeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					EtvaLogicalvolumePeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (EtvaServer) to the collection in $obj2 (EtvaLogicalvolume)
				$obj2->addEtvaServer($obj1);

			} // if joined row is not null

				// Add objects for joined EtvaNode rows

				$key3 = EtvaNodePeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = EtvaNodePeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = EtvaNodePeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					EtvaNodePeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (EtvaServer) to the collection in $obj3 (EtvaNode)
				$obj3->addEtvaServer($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


  static public function getUniqueColumnNames()
  {
    return array();
  }
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * This uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass()
	{
		return EtvaServerPeer::CLASS_DEFAULT;
	}

	/**
	 * Method perform an INSERT on the database, given a EtvaServer or Criteria object.
	 *
	 * @param      mixed $values Criteria or EtvaServer object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseEtvaServerPeer:doInsert:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseEtvaServerPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(EtvaServerPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from EtvaServer object
		}

		if ($criteria->containsKey(EtvaServerPeer::ID) && $criteria->keyContainsValue(EtvaServerPeer::ID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.EtvaServerPeer::ID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

		
    foreach (sfMixer::getCallables('BaseEtvaServerPeer:doInsert:post') as $callable)
    {
      call_user_func($callable, 'BaseEtvaServerPeer', $values, $con, $pk);
    }

    return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a EtvaServer or Criteria object.
	 *
	 * @param      mixed $values Criteria or EtvaServer object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseEtvaServerPeer:doUpdate:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseEtvaServerPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(EtvaServerPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(EtvaServerPeer::ID);
			$selectCriteria->add(EtvaServerPeer::ID, $criteria->remove(EtvaServerPeer::ID), $comparison);

		} else { // $values is EtvaServer object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);
	

    foreach (sfMixer::getCallables('BaseEtvaServerPeer:doUpdate:post') as $callable)
    {
      call_user_func($callable, 'BaseEtvaServerPeer', $values, $con, $ret);
    }

    return $ret;
  }

	/**
	 * Method to DELETE all rows from the server table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(EtvaServerPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(EtvaServerPeer::TABLE_NAME, $con);
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a EtvaServer or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or EtvaServer object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(EtvaServerPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			EtvaServerPeer::clearInstancePool();

			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof EtvaServer) {
			// invalidate the cache for this single object
			EtvaServerPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else {
			// it must be the primary key



			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(EtvaServerPeer::ID, (array) $values, Criteria::IN);

			foreach ((array) $values as $singleval) {
				// we can invalidate the cache for this single object
				EtvaServerPeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			$affectedRows += BasePeer::doDelete($criteria, $con);

			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given EtvaServer object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      EtvaServer $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(EtvaServer $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(EtvaServerPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(EtvaServerPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		$res =  BasePeer::doValidate(EtvaServerPeer::DATABASE_NAME, EtvaServerPeer::TABLE_NAME, $columns);
    if ($res !== true) {
        $request = sfContext::getInstance()->getRequest();
        foreach ($res as $failed) {
            $col = EtvaServerPeer::translateFieldname($failed->getColumn(), BasePeer::TYPE_COLNAME, BasePeer::TYPE_PHPNAME);
        }
    }

    return $res;
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     EtvaServer
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = EtvaServerPeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(EtvaServerPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(EtvaServerPeer::DATABASE_NAME);
		$criteria->add(EtvaServerPeer::ID, $pk);

		$v = EtvaServerPeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(EtvaServerPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(EtvaServerPeer::DATABASE_NAME);
			$criteria->add(EtvaServerPeer::ID, $pks, Criteria::IN);
			$objs = EtvaServerPeer::doSelect($criteria, $con);
		}
		return $objs;
	}

} // BaseEtvaServerPeer

// This is the static code needed to register the MapBuilder for this table with the main Propel class.
//
// NOTE: This static code cannot call methods on the EtvaServerPeer class, because it is not defined yet.
// If you need to use overridden methods, you can add this code to the bottom of the EtvaServerPeer class:
//
// Propel::getDatabaseMap(EtvaServerPeer::DATABASE_NAME)->addTableBuilder(EtvaServerPeer::TABLE_NAME, EtvaServerPeer::getMapBuilder());
//
// Doing so will effectively overwrite the registration below.

Propel::getDatabaseMap(BaseEtvaServerPeer::DATABASE_NAME)->addTableBuilder(BaseEtvaServerPeer::TABLE_NAME, BaseEtvaServerPeer::getMapBuilder());

