<?php

/**
 * Base class that represents a row from the 'volumegroup' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Fri Aug 28 18:22:07 2009
 *
 * @package    lib.model.om
 */
abstract class BaseEtvaVolumegroup extends BaseObject  implements Persistent {


  const PEER = 'EtvaVolumegroupPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        EtvaVolumegroupPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the node_id field.
	 * @var        int
	 */
	protected $node_id;

	/**
	 * The value for the vg field.
	 * @var        string
	 */
	protected $vg;

	/**
	 * The value for the size field.
	 * @var        string
	 */
	protected $size;

	/**
	 * The value for the freesize field.
	 * @var        string
	 */
	protected $freesize;

	/**
	 * @var        EtvaNode
	 */
	protected $aEtvaNode;

	/**
	 * @var        array EtvaLogicalvolume[] Collection to store aggregation of EtvaLogicalvolume objects.
	 */
	protected $collEtvaLogicalvolumes;

	/**
	 * @var        Criteria The criteria used to select the current contents of collEtvaLogicalvolumes.
	 */
	private $lastEtvaLogicalvolumeCriteria = null;

	/**
	 * @var        array EtvaVolumePhysical[] Collection to store aggregation of EtvaVolumePhysical objects.
	 */
	protected $collEtvaVolumePhysicals;

	/**
	 * @var        Criteria The criteria used to select the current contents of collEtvaVolumePhysicals.
	 */
	private $lastEtvaVolumePhysicalCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseEtvaVolumegroup object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [node_id] column value.
	 * 
	 * @return     int
	 */
	public function getNodeId()
	{
		return $this->node_id;
	}

	/**
	 * Get the [vg] column value.
	 * 
	 * @return     string
	 */
	public function getVg()
	{
		return $this->vg;
	}

	/**
	 * Get the [size] column value.
	 * 
	 * @return     string
	 */
	public function getSize()
	{
		return $this->size;
	}

	/**
	 * Get the [freesize] column value.
	 * 
	 * @return     string
	 */
	public function getFreesize()
	{
		return $this->freesize;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     EtvaVolumegroup The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = EtvaVolumegroupPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [node_id] column.
	 * 
	 * @param      int $v new value
	 * @return     EtvaVolumegroup The current object (for fluent API support)
	 */
	public function setNodeId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->node_id !== $v) {
			$this->node_id = $v;
			$this->modifiedColumns[] = EtvaVolumegroupPeer::NODE_ID;
		}

		if ($this->aEtvaNode !== null && $this->aEtvaNode->getId() !== $v) {
			$this->aEtvaNode = null;
		}

		return $this;
	} // setNodeId()

	/**
	 * Set the value of [vg] column.
	 * 
	 * @param      string $v new value
	 * @return     EtvaVolumegroup The current object (for fluent API support)
	 */
	public function setVg($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->vg !== $v) {
			$this->vg = $v;
			$this->modifiedColumns[] = EtvaVolumegroupPeer::VG;
		}

		return $this;
	} // setVg()

	/**
	 * Set the value of [size] column.
	 * 
	 * @param      string $v new value
	 * @return     EtvaVolumegroup The current object (for fluent API support)
	 */
	public function setSize($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->size !== $v) {
			$this->size = $v;
			$this->modifiedColumns[] = EtvaVolumegroupPeer::SIZE;
		}

		return $this;
	} // setSize()

	/**
	 * Set the value of [freesize] column.
	 * 
	 * @param      string $v new value
	 * @return     EtvaVolumegroup The current object (for fluent API support)
	 */
	public function setFreesize($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->freesize !== $v) {
			$this->freesize = $v;
			$this->modifiedColumns[] = EtvaVolumegroupPeer::FREESIZE;
		}

		return $this;
	} // setFreesize()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->node_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->vg = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->size = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->freesize = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 5; // 5 = EtvaVolumegroupPeer::NUM_COLUMNS - EtvaVolumegroupPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating EtvaVolumegroup object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aEtvaNode !== null && $this->node_id !== $this->aEtvaNode->getId()) {
			$this->aEtvaNode = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(EtvaVolumegroupPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = EtvaVolumegroupPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aEtvaNode = null;
			$this->collEtvaLogicalvolumes = null;
			$this->lastEtvaLogicalvolumeCriteria = null;

			$this->collEtvaVolumePhysicals = null;
			$this->lastEtvaVolumePhysicalCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseEtvaVolumegroup:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(EtvaVolumegroupPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			EtvaVolumegroupPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseEtvaVolumegroup:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseEtvaVolumegroup:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(EtvaVolumegroupPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseEtvaVolumegroup:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			EtvaVolumegroupPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aEtvaNode !== null) {
				if ($this->aEtvaNode->isModified() || $this->aEtvaNode->isNew()) {
					$affectedRows += $this->aEtvaNode->save($con);
				}
				$this->setEtvaNode($this->aEtvaNode);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = EtvaVolumegroupPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = EtvaVolumegroupPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += EtvaVolumegroupPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collEtvaLogicalvolumes !== null) {
				foreach ($this->collEtvaLogicalvolumes as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collEtvaVolumePhysicals !== null) {
				foreach ($this->collEtvaVolumePhysicals as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aEtvaNode !== null) {
				if (!$this->aEtvaNode->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aEtvaNode->getValidationFailures());
				}
			}


			if (($retval = EtvaVolumegroupPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collEtvaLogicalvolumes !== null) {
					foreach ($this->collEtvaLogicalvolumes as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collEtvaVolumePhysicals !== null) {
					foreach ($this->collEtvaVolumePhysicals as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = EtvaVolumegroupPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getNodeId();
				break;
			case 2:
				return $this->getVg();
				break;
			case 3:
				return $this->getSize();
				break;
			case 4:
				return $this->getFreesize();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = EtvaVolumegroupPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getNodeId(),
			$keys[2] => $this->getVg(),
			$keys[3] => $this->getSize(),
			$keys[4] => $this->getFreesize(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = EtvaVolumegroupPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setNodeId($value);
				break;
			case 2:
				$this->setVg($value);
				break;
			case 3:
				$this->setSize($value);
				break;
			case 4:
				$this->setFreesize($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = EtvaVolumegroupPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setNodeId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setVg($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setSize($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setFreesize($arr[$keys[4]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(EtvaVolumegroupPeer::DATABASE_NAME);

		if ($this->isColumnModified(EtvaVolumegroupPeer::ID)) $criteria->add(EtvaVolumegroupPeer::ID, $this->id);
		if ($this->isColumnModified(EtvaVolumegroupPeer::NODE_ID)) $criteria->add(EtvaVolumegroupPeer::NODE_ID, $this->node_id);
		if ($this->isColumnModified(EtvaVolumegroupPeer::VG)) $criteria->add(EtvaVolumegroupPeer::VG, $this->vg);
		if ($this->isColumnModified(EtvaVolumegroupPeer::SIZE)) $criteria->add(EtvaVolumegroupPeer::SIZE, $this->size);
		if ($this->isColumnModified(EtvaVolumegroupPeer::FREESIZE)) $criteria->add(EtvaVolumegroupPeer::FREESIZE, $this->freesize);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(EtvaVolumegroupPeer::DATABASE_NAME);

		$criteria->add(EtvaVolumegroupPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of EtvaVolumegroup (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setNodeId($this->node_id);

		$copyObj->setVg($this->vg);

		$copyObj->setSize($this->size);

		$copyObj->setFreesize($this->freesize);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getEtvaLogicalvolumes() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addEtvaLogicalvolume($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getEtvaVolumePhysicals() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addEtvaVolumePhysical($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     EtvaVolumegroup Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     EtvaVolumegroupPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new EtvaVolumegroupPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a EtvaNode object.
	 *
	 * @param      EtvaNode $v
	 * @return     EtvaVolumegroup The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setEtvaNode(EtvaNode $v = null)
	{
		if ($v === null) {
			$this->setNodeId(NULL);
		} else {
			$this->setNodeId($v->getId());
		}

		$this->aEtvaNode = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the EtvaNode object, it will not be re-added.
		if ($v !== null) {
			$v->addEtvaVolumegroup($this);
		}

		return $this;
	}


	/**
	 * Get the associated EtvaNode object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     EtvaNode The associated EtvaNode object.
	 * @throws     PropelException
	 */
	public function getEtvaNode(PropelPDO $con = null)
	{
		if ($this->aEtvaNode === null && ($this->node_id !== null)) {
			$c = new Criteria(EtvaNodePeer::DATABASE_NAME);
			$c->add(EtvaNodePeer::ID, $this->node_id);
			$this->aEtvaNode = EtvaNodePeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aEtvaNode->addEtvaVolumegroups($this);
			 */
		}
		return $this->aEtvaNode;
	}

	/**
	 * Clears out the collEtvaLogicalvolumes collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addEtvaLogicalvolumes()
	 */
	public function clearEtvaLogicalvolumes()
	{
		$this->collEtvaLogicalvolumes = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collEtvaLogicalvolumes collection (array).
	 *
	 * By default this just sets the collEtvaLogicalvolumes collection to an empty array (like clearcollEtvaLogicalvolumes());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initEtvaLogicalvolumes()
	{
		$this->collEtvaLogicalvolumes = array();
	}

	/**
	 * Gets an array of EtvaLogicalvolume objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this EtvaVolumegroup has previously been saved, it will retrieve
	 * related EtvaLogicalvolumes from storage. If this EtvaVolumegroup is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array EtvaLogicalvolume[]
	 * @throws     PropelException
	 */
	public function getEtvaLogicalvolumes($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EtvaVolumegroupPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collEtvaLogicalvolumes === null) {
			if ($this->isNew()) {
			   $this->collEtvaLogicalvolumes = array();
			} else {

				$criteria->add(EtvaLogicalvolumePeer::VOLUMEGROUP_ID, $this->id);

				EtvaLogicalvolumePeer::addSelectColumns($criteria);
				$this->collEtvaLogicalvolumes = EtvaLogicalvolumePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(EtvaLogicalvolumePeer::VOLUMEGROUP_ID, $this->id);

				EtvaLogicalvolumePeer::addSelectColumns($criteria);
				if (!isset($this->lastEtvaLogicalvolumeCriteria) || !$this->lastEtvaLogicalvolumeCriteria->equals($criteria)) {
					$this->collEtvaLogicalvolumes = EtvaLogicalvolumePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastEtvaLogicalvolumeCriteria = $criteria;
		return $this->collEtvaLogicalvolumes;
	}

	/**
	 * Returns the number of related EtvaLogicalvolume objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related EtvaLogicalvolume objects.
	 * @throws     PropelException
	 */
	public function countEtvaLogicalvolumes(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EtvaVolumegroupPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collEtvaLogicalvolumes === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(EtvaLogicalvolumePeer::VOLUMEGROUP_ID, $this->id);

				$count = EtvaLogicalvolumePeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(EtvaLogicalvolumePeer::VOLUMEGROUP_ID, $this->id);

				if (!isset($this->lastEtvaLogicalvolumeCriteria) || !$this->lastEtvaLogicalvolumeCriteria->equals($criteria)) {
					$count = EtvaLogicalvolumePeer::doCount($criteria, $con);
				} else {
					$count = count($this->collEtvaLogicalvolumes);
				}
			} else {
				$count = count($this->collEtvaLogicalvolumes);
			}
		}
		$this->lastEtvaLogicalvolumeCriteria = $criteria;
		return $count;
	}

	/**
	 * Method called to associate a EtvaLogicalvolume object to this object
	 * through the EtvaLogicalvolume foreign key attribute.
	 *
	 * @param      EtvaLogicalvolume $l EtvaLogicalvolume
	 * @return     void
	 * @throws     PropelException
	 */
	public function addEtvaLogicalvolume(EtvaLogicalvolume $l)
	{
		if ($this->collEtvaLogicalvolumes === null) {
			$this->initEtvaLogicalvolumes();
		}
		if (!in_array($l, $this->collEtvaLogicalvolumes, true)) { // only add it if the **same** object is not already associated
			array_push($this->collEtvaLogicalvolumes, $l);
			$l->setEtvaVolumegroup($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this EtvaVolumegroup is new, it will return
	 * an empty collection; or if this EtvaVolumegroup has previously
	 * been saved, it will retrieve related EtvaLogicalvolumes from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in EtvaVolumegroup.
	 */
	public function getEtvaLogicalvolumesJoinEtvaNode($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EtvaVolumegroupPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collEtvaLogicalvolumes === null) {
			if ($this->isNew()) {
				$this->collEtvaLogicalvolumes = array();
			} else {

				$criteria->add(EtvaLogicalvolumePeer::VOLUMEGROUP_ID, $this->id);

				$this->collEtvaLogicalvolumes = EtvaLogicalvolumePeer::doSelectJoinEtvaNode($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(EtvaLogicalvolumePeer::VOLUMEGROUP_ID, $this->id);

			if (!isset($this->lastEtvaLogicalvolumeCriteria) || !$this->lastEtvaLogicalvolumeCriteria->equals($criteria)) {
				$this->collEtvaLogicalvolumes = EtvaLogicalvolumePeer::doSelectJoinEtvaNode($criteria, $con, $join_behavior);
			}
		}
		$this->lastEtvaLogicalvolumeCriteria = $criteria;

		return $this->collEtvaLogicalvolumes;
	}

	/**
	 * Clears out the collEtvaVolumePhysicals collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addEtvaVolumePhysicals()
	 */
	public function clearEtvaVolumePhysicals()
	{
		$this->collEtvaVolumePhysicals = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collEtvaVolumePhysicals collection (array).
	 *
	 * By default this just sets the collEtvaVolumePhysicals collection to an empty array (like clearcollEtvaVolumePhysicals());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initEtvaVolumePhysicals()
	{
		$this->collEtvaVolumePhysicals = array();
	}

	/**
	 * Gets an array of EtvaVolumePhysical objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this EtvaVolumegroup has previously been saved, it will retrieve
	 * related EtvaVolumePhysicals from storage. If this EtvaVolumegroup is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array EtvaVolumePhysical[]
	 * @throws     PropelException
	 */
	public function getEtvaVolumePhysicals($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EtvaVolumegroupPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collEtvaVolumePhysicals === null) {
			if ($this->isNew()) {
			   $this->collEtvaVolumePhysicals = array();
			} else {

				$criteria->add(EtvaVolumePhysicalPeer::VOLUMEGROUP_ID, $this->id);

				EtvaVolumePhysicalPeer::addSelectColumns($criteria);
				$this->collEtvaVolumePhysicals = EtvaVolumePhysicalPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(EtvaVolumePhysicalPeer::VOLUMEGROUP_ID, $this->id);

				EtvaVolumePhysicalPeer::addSelectColumns($criteria);
				if (!isset($this->lastEtvaVolumePhysicalCriteria) || !$this->lastEtvaVolumePhysicalCriteria->equals($criteria)) {
					$this->collEtvaVolumePhysicals = EtvaVolumePhysicalPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastEtvaVolumePhysicalCriteria = $criteria;
		return $this->collEtvaVolumePhysicals;
	}

	/**
	 * Returns the number of related EtvaVolumePhysical objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related EtvaVolumePhysical objects.
	 * @throws     PropelException
	 */
	public function countEtvaVolumePhysicals(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EtvaVolumegroupPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collEtvaVolumePhysicals === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(EtvaVolumePhysicalPeer::VOLUMEGROUP_ID, $this->id);

				$count = EtvaVolumePhysicalPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(EtvaVolumePhysicalPeer::VOLUMEGROUP_ID, $this->id);

				if (!isset($this->lastEtvaVolumePhysicalCriteria) || !$this->lastEtvaVolumePhysicalCriteria->equals($criteria)) {
					$count = EtvaVolumePhysicalPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collEtvaVolumePhysicals);
				}
			} else {
				$count = count($this->collEtvaVolumePhysicals);
			}
		}
		$this->lastEtvaVolumePhysicalCriteria = $criteria;
		return $count;
	}

	/**
	 * Method called to associate a EtvaVolumePhysical object to this object
	 * through the EtvaVolumePhysical foreign key attribute.
	 *
	 * @param      EtvaVolumePhysical $l EtvaVolumePhysical
	 * @return     void
	 * @throws     PropelException
	 */
	public function addEtvaVolumePhysical(EtvaVolumePhysical $l)
	{
		if ($this->collEtvaVolumePhysicals === null) {
			$this->initEtvaVolumePhysicals();
		}
		if (!in_array($l, $this->collEtvaVolumePhysicals, true)) { // only add it if the **same** object is not already associated
			array_push($this->collEtvaVolumePhysicals, $l);
			$l->setEtvaVolumegroup($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this EtvaVolumegroup is new, it will return
	 * an empty collection; or if this EtvaVolumegroup has previously
	 * been saved, it will retrieve related EtvaVolumePhysicals from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in EtvaVolumegroup.
	 */
	public function getEtvaVolumePhysicalsJoinEtvaPhysicalvolume($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EtvaVolumegroupPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collEtvaVolumePhysicals === null) {
			if ($this->isNew()) {
				$this->collEtvaVolumePhysicals = array();
			} else {

				$criteria->add(EtvaVolumePhysicalPeer::VOLUMEGROUP_ID, $this->id);

				$this->collEtvaVolumePhysicals = EtvaVolumePhysicalPeer::doSelectJoinEtvaPhysicalvolume($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(EtvaVolumePhysicalPeer::VOLUMEGROUP_ID, $this->id);

			if (!isset($this->lastEtvaVolumePhysicalCriteria) || !$this->lastEtvaVolumePhysicalCriteria->equals($criteria)) {
				$this->collEtvaVolumePhysicals = EtvaVolumePhysicalPeer::doSelectJoinEtvaPhysicalvolume($criteria, $con, $join_behavior);
			}
		}
		$this->lastEtvaVolumePhysicalCriteria = $criteria;

		return $this->collEtvaVolumePhysicals;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collEtvaLogicalvolumes) {
				foreach ((array) $this->collEtvaLogicalvolumes as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collEtvaVolumePhysicals) {
				foreach ((array) $this->collEtvaVolumePhysicals as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collEtvaLogicalvolumes = null;
		$this->collEtvaVolumePhysicals = null;
			$this->aEtvaNode = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseEtvaVolumegroup:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseEtvaVolumegroup::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseEtvaVolumegroup
