#!/usr/bin/perl

use strict;

use ETVOIP;

use ETVA::Utils;
use Data::Dumper;

use ETVA::GuestAgent::Management;


my %CONF = ( "CFG_FILE"=>"/etc/sysconfig/etva-etvoip/etvoipd.conf" );

sub main {
    $CONF{"CFG_FILE"} = $ENV{'CFG_FILE'} if( $ENV{'CFG_FILE'} );
    loadfunc();
    launch_agent();
}

sub loadfunc {
    %CONF = ETVA::Utils::get_conf(1,$CONF{"CFG_FILE"});
}
sub launch_agent {

    # get network interface to initialize agent with macaddress
    $CONF{'macaddr'} = ETVA::Utils::getmacaddr();

    # register func handlers
    $CONF{'_register_handler'} = \&register_handler;

    my $dispatcher = $CONF{'_dispatcher'} = "ETVOIPDispatcher";

    my $agent = ETVA::GuestAgent::Management->new( %CONF );

    $agent->mainLoop();
}

sub register_handler {
    my $self = shift;

    # initialized on CentralManagement 
    if( $self->{'cm_uri'} ){

        # get ETVOIP active modules
        my %Mod = ETVOIP->get_activemodules();
        my @services = ();
        for my $m (keys %Mod){
            my $pmod = $Mod{"$m"};            

            eval "require $pmod";
            if( !$@ ){
                my %params = ( "dispatcher"=>$pmod );
                eval { 
                    # trie run load config of module
                    my %C = $pmod->get_config();                    
                    if( %C ){                        
                        # send parameters from config of module
                        %params = (%params,%C);
                    }
                };
                push(@services, { name=>$m, description=>"$m ($pmod)",
                                    params=>\%params } );
            } else{
                plog "etvoip - Perl module '$pmod' required!";
            }
        }
        my $now = nowStr();
        plogNow("init Agent with macaddr=",$self->{'macaddr'});
        plogNow(" services = ",Dumper(\@services));

        my $R = $self->call( $self->{'cm_namespace'},
                                 "initAgentServices",
                                    name=>'ETVOIP',
                                    ip=>$self->{'LocalIP'},
                                    port=>$self->{'LocalPort'},
                                    macaddr=>$self->{'macaddr'},
                                    services=>\@services
                                );
        if( !$R || $R->{'_error_'} ){
                plogNow("Cant connect to CentralManagement.\nInitialization Agent 'etvoip' aborted!");
        } else {
            plogNow($R->{'return'}{'success'});
            if( ref($R->{'return'}) && $R->{'return'}{'success'} && ( $R->{'return'}{'success'} ne 'false' )){
                plogNow("$now - ETVOIP Agent register with success on CentralManagement");


                # Reset
                if( $R->{'return'}{'reset'} ){
                    my $response = ETVOIP->set_backupconf( '_url'=>"$R->{'return'}{'backup_url'}" );

                    plogNow("RESPONSE ",isOk($response),Dumper($response));

                    # send reset/restore ok
                    if(!isError($response)){
                        plogNow("RESPONSE OKKKK",Dumper($response));
                        my $reset_ok = $response;
                        my $RR = $self->call( $self->{'cm_namespace'},
                                        'restoreManagAgent',
                                        macaddr=>$self->{'macaddr'},
                                        ok=>{ 'oktype'=>$reset_ok->{'_oktype_'}, 'okmsg'=>$reset_ok->{'_okmsg_'} }
                                    );
                    }
                    
                }
                return 1;
            }else{
                plogNow("$now - ETVOIP Agent NOT registered with success on CentralManagement");
            }
        }      
    }
    return 0;
}
main();
1;
