#!/usr/bin/perl

use strict;

use ETVA::Agent::SOAPFork;
use ETVA::Client::SOAP::HTTP;
use ETVOIP;
use ETVA::Utils;
use Data::Dumper;

my %CONF = ( "CFG_FILE"=>"/etc/sysconfig/etva-etvoip/etvoipd.conf" );

sub main {
    $CONF{"CFG_FILE"} = $ENV{'CFG_FILE'} if( $ENV{'CFG_FILE'} );
    loadfunc();
    launch_agent();
}

sub loadfunc {
    %CONF = ETVA::Utils::get_conf(1,$CONF{"CFG_FILE"});
}
sub launch_agent {

    # get network interface to initialize agent with macaddress
    $CONF{'macaddr'} = ETVA::Utils::getmacaddr();

    # register func handlers
    $CONF{'_register_handler'} = \&register_handler;

    require ETVOIPDispatcher;

    my $dispatcher = $CONF{'_dispatcher'} = "ETVOIPDispatcher";

    my $Agent = ETVA::Agent::SOAPFork->new( %CONF );

    $Agent->mainLoop();
}
sub register_handler {
    my ($agent) = @_;

    # initialized on CentralManagement 
    if( $agent->{'cm_uri'} ){

        # get ETVOIP active modules
        my %Mod = ETVOIP->get_activemodules();
        my @services = ();
        for my $m (keys %Mod){
            my $pmod = $Mod{"$m"};            

            eval "require $pmod";
            if( !$@ ){
                my %params = ( "dispatcher"=>$pmod );
                eval { 
                    # trie run load config of module
                    my %C = $pmod->get_config();                    
                    if( %C ){                        
                        # send parameters from config of module
                        %params = (%params,%C);
                    }
                };
                push(@services, { name=>$m, description=>"$m ($pmod)",
                                    params=>\%params } );
            } else{
                plog "etvoip - Perl module '$pmod' required!";
            }
        }
        my $now = nowStr();
        plog("$now - init Agent with macaddr=",$agent->{'macaddr'});
        plog(" services = ",Dumper(\@services));

        my $R = new ETVA::Client::SOAP::HTTP( uri => $agent->{'cm_uri'} )
                        -> call( $agent->{'cm_namespace'},
                                 "initAgentServices",
                                    name=>'ETVOIP',
                                    ip=>$agent->{'LocalIP'},
                                    port=>$agent->{'LocalPort'},
                                    macaddr=>$agent->{'macaddr'},
                                    services=>\@services
                                );
        if( !$R || $R->{'_error_'} ){
                plog("Cant connect to CentralManagement.\nInitialization Agent 'etvoip' aborted!");
        } else {
            plog($R->{'return'}{'success'});
            if( ref($R->{'return'}) && $R->{'return'}{'success'} && ( $R->{'return'}{'success'} ne 'false' )){
                plog("$now - ETVOIP Agent register with success on CentralManagement");


                # Reset
                if( $R->{'return'}{'reset'} ){
                    my $response = ETVOIP->set_backupconf( '_url'=>"$R->{'return'}{'backup_url'}" );

                    plog("RESPONSE ",isOk($response),Dumper($response));

                    # send reset/restore ok
                    if(!isError($response)){
                        plog("RESPONSE OKKKK",Dumper($response));
                        my $reset_ok = $response;
                        my $RR = new ETVA::Client::SOAP::HTTP( uri => $agent->{'cm_uri'} )
                            -> call( $agent->{'cm_namespace'},
                                        'restoreManagAgent',
                                        macaddr=>$agent->{'macaddr'},
                                        ok=>{ 'oktype'=>$reset_ok->{'_oktype_'}, 'okmsg'=>$reset_ok->{'_okmsg_'} }
                                    );
                    }
                    
                }

                

            }else{
                plog("$now - ETVOIP Agent NOT registered with success on CentralManagement");
            }
        }      
    }
}
main();
1;
