#!/usr/bin/perl

use strict;

use ETVA::Agent::SOAPFork;
use ETVA::Client::SOAP::HTTP;
use ETVA::Utils;
use ETMS;

#use Agent::SOAP;
#use Client::SOAP::HTTP;
#use Utils;
use Data::Dumper;

my %CONF = ( "CFG_FILE"=>"/etc/sysconfig/etva-etms/etmsd.conf" );

sub main {
    $CONF{"CFG_FILE"} = $ENV{'CFG_FILE'} if( $ENV{'CFG_FILE'} );
    loadfunc();
    launch_agent();
}

sub loadfunc {
    %CONF = ETVA::Utils::get_conf(1,$CONF{"CFG_FILE"});
}
sub launch_agent {

    # get network interface to initialize agent with macaddress
    $CONF{'macaddr'} = ETVA::Utils::getmacaddr();
        
    my $macaddr = $CONF{'macaddr'} = lc $CONF{'macaddr'};
    
    # register func handlers
    $CONF{'_register_handler'} = \&register_handler;

    require ETMS;

    my $dispatcher = $CONF{'_dispatcher'} = "ETMS";

    my $Agent =  ETVA::Agent::SOAPFork->new( %CONF );

    $Agent->mainLoop();
}
sub register_handler {
    my ($agent) = @_;

    # initialized on CentralManagement 
    if( $agent->{'cm_uri'} ){

	my %domain = (name => "domain");
	my %mailbox = (name => "mailbox");
    my %server = (name => "server");
	my @services;
	unshift @services, \%domain;
	unshift @services, \%mailbox;
    unshift @services, \%server;
	print Dumper(\@services);
		
	my $now = now();
	plog("$now - init Agent with macaddr=",$agent->{'macaddr'});
	plog(" services = ",Dumper(\@services));

        my $R = new ETVA::Client::SOAP::HTTP( uri => $agent->{'cm_uri'}, debug=>1 )
                    -> call( $agent->{'cm_namespace'},
                             "initAgentServices",
                                name=>'ETMS',
                                ip=>$agent->{'LocalIP'},
                                port=>$agent->{'LocalPort'},
                                macaddr=>$agent->{'macaddr'},
                                services=>\@services
                            );
        if( !$R || $R->{'_error_'} ){
            plog("Cant connect to CentralManagement.\nInitialization Agent 'etms' aborted!");
        } else {            

            if( ref($R->{'return'}) && $R->{'return'}{'success'}){
                plog("$now - ETMS Agent register with success on CentralManagement");
            }

            # restore
            my $resetError = 0;
            # Reset
            if( $R->{'return'}{'reset'} ){
                print "ETMS : calling set_backupconf\n";
                ETMS->set_backupconf( '_url'=>"$R->{'return'}{'backup_url'}" );
                # load old conf
                my %old_CONF = ETVA::Utils::get_conf(1,$CONF{"CFG_FILE"});
                # merge with new conf
                %CONF = (%old_CONF, %CONF);
                # save to file
                ETVA::Utils::set_conf($CONF{"CFG_FILE"},%CONF);


                # TODO restart service
            }

            if( !$resetError && $R->{'return'}{'reset'} ){
                my $reset_ok = retOk("_OK_","ok");
                my $RR = new ETVA::Client::SOAP::HTTP( uri => $agent->{'cm_uri'} )
                        -> call( $agent->{'cm_namespace'},
                                   'restoreManagAgent',
                                    macaddr=>$agent->{'macaddr'},
                                    ok=>{ 'oktype'=>$reset_ok->{'_oktype_'}, 'okmsg'=>$reset_ok->{'_okmsg_'} }
                               );
            }

        }
    }
}
main();
1;
