#!/bin/bash

VM=`dmesg | grep -i qemu`

if [ "$VM" == "" ]; then
    cd /srv/lcdagent
    exec > /var/log/lcdagent/lcdagent.log 2>&1
    CFG_FILE="/etc/sysconfig/lcdagent/lcdagent.ini" \
        exec /usr/bin/perl lcdagentd
else
    touch /service/lcdagent/down && svc -dk /service/lcdagent
fi
