#!/bin/bash

# only run lcdagent on real hardware
if [ "`virt-what`" != "" ]; then # virtual machine
    touch /service/lcdagent/down /service/lcdagent/log/down
    svc -d /service/lcdagent/log
    svc -d /service/lcdagent
else
    cd /srv/lcdagent
    exec > /var/log/lcdagent/lcdagent.log 2>&1
    CFG_FILE="/etc/sysconfig/lcdagent/lcdagent.ini" \
	exec /usr/bin/perl lcdagentd
fi
