<?php



/**
 * Skeleton subclass for performing query and update operations on the 'server_assign' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Mon Aug 20 15:39:25 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class EtvaServerAssignPeer extends BaseEtvaServerAssignPeer {

} // EtvaServerAssignPeer
