<?php

require 'lib/model/om/BaseEtvaPermissionUser.php';


/**
 * Skeleton subclass for representing a row from the 'etvaperm_user' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Sep  7 16:06:34 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class EtvaPermissionUser extends BaseEtvaPermissionUser {

} // EtvaPermissionUser
