<?php

require 'lib/model/om/BaseEtvaClusterPeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'cluster' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * Tue Jul  6 09:44:12 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class EtvaClusterPeer extends BaseEtvaClusterPeer {
    const _DEFAULT_CLUSTER_ = 'Default';
    const _ERR_DEFAULT_CLUSTER_ = 'Could not find default cluster. %info%';
    const _ERR_CLUSTER_ = 'Could not find cluster. %info%';

    public static function retrieveDefaultCluster()
    {
        $c = new Criteria();
        $c->add(self::ISDEFAULTCLUSTER,1);
        $cluster = self::doSelectOne($c);
        if(!$cluster) $cluster = self::createDefaultCluster();
        
        return $cluster;
    }

    public static function createDefaultCluster()
    {
        $c = new Criteria();
        $c->add(self::NAME,self::_DEFAULT_CLUSTER_);
        $cluster = self::doSelectOne($c);
        if(!$cluster) $cluster = new EtvaCluster();
        $cluster->setIsdefaultcluster(1);
        $cluster->setName(self::_DEFAULT_CLUSTER_);
        $cluster->save();
        return $cluster;       
        
    }
    

} // EtvaClusterPeer
