<?php

require 'lib/model/om/BaseEtvaNodeLogicalvolumePeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'node_logicalvolume' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * Tue Jul  6 16:05:28 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class EtvaNodeLogicalvolumePeer extends BaseEtvaNodeLogicalvolumePeer {

} // EtvaNodeLogicalvolumePeer
