<?php



/**
 * Skeleton subclass for representing a row from the 'pool' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Mon Aug  5 17:35:56 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class EtvaPool extends BaseEtvaPool {

  /*
   * returns storage pool representation for sending to VA
   */
  public function _VA()
  {
      $pool_VA = array(
                         'name' => $this->getName(),
                         'type' => $this->getPoolType(),
                         'target_path' => $this->getTargetPath()
      );
      $pool_VA['uuid'] = $this->getUuid();
      $pool_VA['source_device'] = $this->getSourceDevice();
      $pool_VA['source_host'] = $this->getSourceHost();
      $pool_VA['source_dir'] = $this->getSourceDir();
      $pool_VA['source_format'] = $this->getSourceFormat();
      return $pool_VA;
  }
} // EtvaPool
