<?php

require 'lib/model/om/BaseEtvaServerLogicalPeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'server_logical' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * Fri May 28 16:33:12 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class EtvaServerLogicalPeer extends BaseEtvaServerLogicalPeer {

  const _DEFAULT_DISK_TYPE_   = 'ide';

   /*
   * gets first logicalvolume (boot disk)
   */
  public function getBootDisk($server_id)
  {
      $criteria = new Criteria();
      $criteria->add(self::SERVER_ID,$server_id);
      $result = self::doSelectOne($criteria);
      $first_lv = $result->getEtvaLogicalvolume();
      
      return $first_lv;
  }

} // EtvaServerLogicalPeer
