<?php



/**
 * Skeleton subclass for performing query and update operations on the 'asynchronous_job' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Tue Nov 19 17:37:01 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class EtvaAsynchronousJobPeer extends BaseEtvaAsynchronousJobPeer {

} // EtvaAsynchronousJobPeer
