<?php

require 'lib/model/om/BaseEtvaEvent.php';


/**
 * Skeleton subclass for representing a row from the 'event' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * Wed Jul 14 17:52:30 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class EtvaEvent extends BaseEtvaEvent {

} // EtvaEvent
