<?php

require 'lib/model/om/BaseEtvaPermissionNodePeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'etvaperm_node' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Oct  3 14:26:37 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class EtvaPermissionNodePeer extends BaseEtvaPermissionNodePeer {

} // EtvaPermissionNodePeer
