<?php

require 'lib/model/om/BaseEtvaPermissionPeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'etvaperm' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Sep  7 16:06:34 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class EtvaPermissionPeer extends BaseEtvaPermissionPeer {
    const _ERR_NOTFOUND_ID_   = 'Permission with ID %id% could not be found';
} // EtvaPermissionPeer
