<?php

require 'lib/model/om/BaseEtvaVncPort.php';


/**
 * Skeleton subclass for representing a row from the 'vnc_port' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Jun  6 17:08:54 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class EtvaVncPort extends BaseEtvaVncPort {

} // EtvaVncPort
