<?php


/**
 * This class adds structure of 'physicalvolume' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Fri Aug 28 18:22:07 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class EtvaPhysicalvolumeMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.EtvaPhysicalvolumeMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(EtvaPhysicalvolumePeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(EtvaPhysicalvolumePeer::TABLE_NAME);
		$tMap->setPhpName('EtvaPhysicalvolume');
		$tMap->setClassname('EtvaPhysicalvolume');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addForeignKey('NODE_ID', 'NodeId', 'INTEGER', 'node', 'ID', true, null);

		$tMap->addColumn('NAME', 'Name', 'VARCHAR', false, 255);

		$tMap->addColumn('DEVICE', 'Device', 'VARCHAR', false, 255);

		$tMap->addColumn('DEVSIZE', 'Devsize', 'BIGINT', false, null);

		$tMap->addColumn('PV', 'Pv', 'VARCHAR', false, 255);

		$tMap->addColumn('PVSIZE', 'Pvsize', 'BIGINT', false, null);

		$tMap->addColumn('PVFREESIZE', 'Pvfreesize', 'BIGINT', false, null);

		$tMap->addColumn('PVINIT', 'Pvinit', 'INTEGER', false, null);

		$tMap->addColumn('STORAGE_TYPE', 'StorageType', 'VARCHAR', false, 255);

		$tMap->addColumn('ALLOCATABLE', 'Allocatable', 'INTEGER', false, null);

	} // doBuild()

} // EtvaPhysicalvolumeMapBuilder
